update after operation

diff --git a/conf-init.install b/conf-init.install
--- a/conf-init.install
+++ b/conf-init.install
@@ -16,24 +16,23 @@ S_PATH_INSTALL_CONF=${S_PATH_INSTALL}/conf
 file_conf_server=${S_PATH_INSTALL}/conf-server.install
 file_install_server=${S_PATH_INSTALL_CONF}/server.conf
 
+[ ${USER} != root ] && _SUDO=sudo
+
 
 ########################  PRE
-
-[ "$USER" != root ] && echo -e "${redb}[error] You have to run this script under root privileges${cclear}" && exit 1
 
 ! [ -d ${S_PATH_SCRIPT} ] && echo -e "${redb}[error] Unable to find path script: '${S_PATH_SCRIPT}'${cclear}" && exit 1
 
 echo -e "${blueb}----------  initialisation${cclear}"
 
 echo -n "unable to find initial configuration, Do you want to do it? (y)/n: "
-read answer
-[ "$answer" = "n" ] && exit
+read answer && [ "${answer}" = n ] && exit
 
 
 echo -e "${blueb}----------  required files${cclear}"
 
 for file in "${file_conf_server}" "${file_install_server}"; do
-	! [ -f ${file} ] && echo -e "${redb}error - unable to find file: '${file}'${cclear}" && exit 1
+	! ${_SUDO} [ -f ${file} ] && echo -e "${redb}[error] unable to find file: '${file}'${cclear}" && exit 1
 done
 
 
@@ -41,37 +40,45 @@ done
 
 echo -e "${blueb}----------  log path${cclear}"
 
-[ -d "$_PATH_LOG" ] && mkdir -p "$_PATH_LOG"
+[ -d "${_PATH_LOG}" ] || ${_SUDO} mkdir -p "${_PATH_LOG}"
+[ ${USER} != root ] && sudo chown :1000 "${_PATH_LOG}" && sudo chmod g+rw "${_PATH_LOG}"
 
 
 echo -e "${blueb}----------  paths rights${cclear}"
 
 # install path
 path=${_PATH_BASE}
-eval chown root:root -R ${path}
-eval chmod o-rwx -R ${path}
+${_SUDO} chown root:root -R ${path}
+${_SUDO} chmod g+rw,o-rwx -R ${path}
 
 # scripts path
 path=${S_PATH_SCRIPT}
-eval chown root:root -R ${path}
-eval chmod o-rwx -R ${path}
+${_SUDO} chown root:root -R ${path}
+${_SUDO} chmod g+rw,o-rwx -R ${path}
 
 
 echo -e "${blueb}----------  conf rights${cclear}"
 
 for path in "${S_PATH_CONF}/ssl/private" "${S_PATH_CONF}/ssl/certs"; do
-	! [ -d "$path" ] && mkdir -p "$path"
+	! ${_SUDO} [ -d "$path" ] && ${_SUDO} mkdir -p "$path"
 done
-find "${S_PATH_CONF}" -type d -exec chmod 750 "{}" \;
-find "${S_PATH_CONF}" -type f -exec chmod 640 "{}" \;
-find "${S_PATH_CONF}/ssl/private" -type d -exec chmod 700 "{}" \;
-find "${S_PATH_CONF}/ssl/private" -type f -exec chmod 600 "{}" \;
-[ -h /server ] || ln -s /etc/server /server
+${_SUDO} find "${S_PATH_CONF}" -type d -exec chmod 770 "{}" \;
+${_SUDO} find "${S_PATH_CONF}" -maxdepth 1 -type f -exec chmod 660 "{}" \;
+${_SUDO} find "${S_PATH_CONF}/ssl/private" -type d -exec chmod 700 "{}" \;
+${_SUDO} find "${S_PATH_CONF}/ssl/private" -type f -exec chmod 600 "{}" \;
+[ -h /server ] || ${_SUDO} ln -s /etc/server /server
+
+if [ ${USER} != root ]; then
+	echo -e "${blueb}----------  non root rights${cclear}"
+	for path in ${S_PATH_CONF} ${_PATH_BASE} ${S_PATH_SCRIPT}; do
+		sudo chown 0:1000 -R "${path}"
+	done
+	sudo find "${S_PATH_CONF}" -maxdepth 1 -type f -exec chown 0:1000 "{}" \;
+fi
 
 echo -e "${blueb}----------  server.conf${cclear}"
 
-_keepmvts ${S_GLOBAL_CONF}
-cp -a "${file_install_server}" "${S_GLOBAL_CONF}"
+[ -f "${S_GLOBAL_CONF}" ] || ${_SUDO} cp -a "${file_install_server}" "${S_GLOBAL_CONF}"
 
 echo "If you want to use a specific 'server.conf' , put this file to '${S_GLOBAL_CONF}'"
 echo "cp /usr/local/install/conf/server.conf-ovh /etc/server/server.conf"
@@ -82,7 +89,7 @@ echo -e "${blueb}----------  install files${cclear}"
 
 files="${S_FILE_INSTALL_CONF} ${S_FILE_INSTALL_DONE}"
 for file in ${files}; do
-	! [ -f "${file}" ] && touch "${file}"
+	! [ -f "${file}" ] && _touchr "${file}"
 done
 
 . ${S_FILE_INSTALL_CONF}
@@ -102,4 +109,4 @@ _echoT "----------  server settings"
 
 _PART=conf-init
 _echoT "===================== ${_PART} end"
-_eval _partadd "${_PART}" "${S_FILE_INSTALL_DONE}"
+_partadd "${_PART}" "${S_FILE_INSTALL_DONE}"
