conf: modify global variables - S_HOST_DHCP_MIN S_HOST_DHCP_MAX - S_HOST_PORT_PRE_SSH S_HOST_PORT_PRE_HTTP S_HOST_PORT_PRE_HTTPS - S_DB_USER_HTTP S_DB_USER_DEV

diff --git a/conf-init.install b/conf-init.install
--- a/conf-init.install
+++ b/conf-init.install
@@ -8,6 +8,8 @@ echo -e "${blueb}==========================================  ${_PART}${cclear}"
 
 ########################  DATA
 
+echo -e "${blueb}----------  data${cclear}"
+
 S_PATH_INSTALL=`dirname "$(readlink -e "${BASH_SOURCE[0]}")"`
 S_PATH_INSTALL_CONF=${S_PATH_INSTALL}/conf
 S_PATH_SCRIPT=/usr/local/bs
@@ -20,7 +22,7 @@ file_install_server=${S_PATH_INSTALL_CONF}/server.conf
 
 [ "$USER" != root ] && echo -e "${redb}[error] You have to run this script under root privileges${cclear}" && exit 1
 
-[ -d ${S_PATH_SCRIPT} ] || echo -e "${redb}[error] Unable to find path script: '${S_PATH_SCRIPT}'${cclear}" && exit 1
+! [ -d ${S_PATH_SCRIPT} ] && echo -e "${redb}[error] Unable to find path script: '${S_PATH_SCRIPT}'${cclear}" && exit 1
 
 echo -e "${blueb}----------  initialisation${cclear}"
 
@@ -47,13 +49,13 @@ echo -e "${blueb}----------  paths rights${cclear}"
 
 # install path
 path=${_PATH_BASE}
-_eval chown root:root -R ${path}
-_eval chmod o-rwx -R ${path}
+eval chown root:root -R ${path}
+eval chmod o-rwx -R ${path}
 
 # scripts path
 path=${S_PATH_SCRIPT}
-_eval chown root:root -R ${path}
-_eval chmod o-rwx -R ${path}
+eval chown root:root -R ${path}
+eval chmod o-rwx -R ${path}
 
 
 echo -e "${blueb}----------  conf rights${cclear}"
