firewall: - forward traffic from loopback to proxy - modify firewall to iptables-friewall

diff --git a/conf-init.install b/conf-init.install
--- a/conf-init.install
+++ b/conf-init.install
@@ -9,16 +9,18 @@ echo -e "${blueb}==========================================  ${_PART}${cclear}"
 ########################  DATA
 
 S_PATH_INSTALL=`dirname "$(readlink -e "${BASH_SOURCE[0]}")"`
-S_PATH_INSTALL_CONF="${S_PATH_INSTALL}/conf"
+S_PATH_INSTALL_CONF=${S_PATH_INSTALL}/conf
+S_PATH_SCRIPT=/usr/local/bs
 
-file_conf_server="${S_PATH_INSTALL}/conf-server.install"
-file_install_server="${S_PATH_INSTALL_CONF}/server.conf"
+file_conf_server=${S_PATH_INSTALL}/conf-server.install
+file_install_server=${S_PATH_INSTALL_CONF}/server.conf
 
 
 ########################  PRE
 
-# exit
-[ "$USER" != root ] && echo -e "${redb}You have to run this script under root privileges${cclear}" && exit 1
+[ "$USER" != root ] && echo -e "${redb}[error] You have to run this script under root privileges${cclear}" && exit 1
+
+[ -d ${S_PATH_SCRIPT} ] || echo -e "${redb}[error] Unable to find path script: '${S_PATH_SCRIPT}'${cclear}" && exit 1
 
 echo -e "${blueb}----------  initialisation${cclear}"
 
@@ -41,7 +43,20 @@ echo -e "${blueb}----------  log path${cclear}"
 [ -d "$_PATH_LOG" ] && mkdir -p "$_PATH_LOG"
 
 
-echo -e "${blueb}----------  ssl paths${cclear}"
+echo -e "${blueb}----------  paths rights${cclear}"
+
+# install path
+path=${_PATH_BASE}
+_eval chown root:root -R ${path}
+_eval chmod -grwx -R ${path}
+
+# scripts path
+path=${S_PATH_SCRIPT}
+_eval chown root:root -R ${path}
+_eval chmod -grwx -R ${path}
+
+
+echo -e "${blueb}----------  conf rights${cclear}"
 
 for path in "${S_PATH_CONF}/ssl/private" "${S_PATH_CONF}/ssl/certs"; do
 	! [ -d "$path" ] && mkdir -p "$path"
