global: modify colors & _echoT _echot _ echoW

diff --git a/conf-init.install b/conf-init.install
--- a/conf-init.install
+++ b/conf-init.install
@@ -5,47 +5,34 @@
 _PART=conf-init
 echo -e "${cyanb}==========================================  ${_PART}${cclear}"
 
-
-########################  DATA
-
-echo -e "${cyan}----------  data${cclear}"
+########################  REQUIRED
 
 S_PATH_INSTALL=`dirname "$(readlink -e "${BASH_SOURCE[0]}")"`
 S_PATH_INSTALL_CONF=${S_PATH_INSTALL}/conf
 
 file_conf_server=${S_PATH_INSTALL}/conf-server.install
 file_install_server=${S_PATH_INSTALL_CONF}/server.conf
+file_install_server_ovh=${S_PATH_INSTALL_CONF}/server-ovh.conf
 
-[ ${USER} != root ] && _SUDO=sudo
-
-
-########################  PRE
+for file in ${file_conf_server} ${file_install_server} ${file_install_server_ovh}; do
+	! ${_SUDO} [ -f "${file}" ] && echo -e "${redb}[error] Unable to find file: ${file}${cclear}" && exit 1
+done
 
 ! [ -d ${S_PATH_SCRIPT} ] && echo -e "${redb}[error] Unable to find path script: '${S_PATH_SCRIPT}'${cclear}" && exit 1
 
-echo -e "${cyan}----------  initialisation${cclear}"
+########################  DATA
 
-echo -n "unable to find initial configuration, Do you want to do it? (y)/n: "
-read answer && [ "${answer}" = n ] && exit
+[ ${USER} != root ] && _SUDO=sudo
 
+echo -e "${cyan}----------  data${cclear}"
 
-echo -e "${cyan}----------  required files${cclear}"
-
-for file in "${file_conf_server}" "${file_install_server}"; do
-	! ${_SUDO} [ -f ${file} ] && echo -e "${redb}[error] unable to find file: '${file}'${cclear}" && exit 1
-done
-
+echo "Unable to find initial configuration"
+echo -n "Do you want to copy ovh configuration? (Y/n): "
+read answer && copy_file_install=${answer:-y} && copy_file_install=${copy_file_install/n/}
 
 ########################  MAIN
 
-echo -e "${cyan}----------  log path${cclear}"
-
-[ -d "${_PATH_LOG}" ] || ${_SUDO} mkdir -p "${_PATH_LOG}"
-[ ${USER} != root ] && sudo chown :1000 "${_PATH_LOG}" && sudo chmod g+rw "${_PATH_LOG}"
-
-
 echo -e "${cyan}----------  paths rights${cclear}"
-
 # install path
 path=${_PATH_BASE}
 ${_SUDO} chown root:root -R ${path}
@@ -56,9 +43,7 @@ path=${S_PATH_SCRIPT}
 ${_SUDO} chown root:root -R ${path}
 ${_SUDO} chmod g+rw,o-rwx -R ${path}
 
-
 echo -e "${cyan}----------  conf rights${cclear}"
-
 for path in "${S_PATH_CONF}/ssl/private" "${S_PATH_CONF}/ssl/certs"; do
 	! ${_SUDO} [ -d "$path" ] && ${_SUDO} mkdir -p "$path"
 done
@@ -76,34 +61,18 @@ if [ ${USER} != root ]; then
 	sudo find "${S_PATH_CONF}" -maxdepth 1 -type f -exec chown 0:1000 "{}" \;
 fi
 
-echo -e "${cyan}----------  server.conf${cclear}"
-
-[ -f "${S_GLOBAL_CONF}" ] || ${_SUDO} cp -a "${file_install_server}" "${S_GLOBAL_CONF}"
-
-echo "If you want to use a specific 'server.conf' , put this file to '${S_GLOBAL_CONF}'"
-echo "cp /usr/local/install/conf/server.conf-ovh /etc/server/server.conf"
-echo -n "and valid to continue : " && read _ANSWER
+if ! [ -f "${S_GLOBAL_CONF}" ]; then
+	echo -e "${cyan}----------  server.conf${cclear}"
+	${_SUDO} cp -a "${file_install_server}" "${S_GLOBAL_CONF}"
+	[ "${copy_file_install}" ] && ${_SUDO} cp -a ${file_install_server_ovh} ${S_GLOBAL_CONF}
+fi
 . ${S_GLOBAL_CONF}
 
-echo -e "${cyan}----------  install files${cclear}"
-
-files="${S_FILE_INSTALL_CONF} ${S_FILE_INSTALL_DONE}"
-for file in ${files}; do
-	! [ -f "${file}" ] && _touchr "${file}"
-done
-
-. ${S_FILE_INSTALL_CONF}
-
-
 echo -e "${cyan}----------  fd open${cclear}"
-
 _redirect
 
-
 _echot "------------------  server settings"
-
 . "${file_conf_server}"
-
 
 ########################  END
 
diff --git a/sub/lxd-alpine-mail.install b/sub/lxd-alpine-mail.install
--- a/sub/lxd-alpine-mail.install
+++ b/sub/lxd-alpine-mail.install
@@ -17,11 +17,18 @@ lxc list -f csv -c n | grep -q ^${S_SERVICE[log]}$ || _exite "Unable to find con
 
 _echot "------------------ select"
 
-anstmp=${S_DOMAIN_FQDN} && _askno "Domain name to use (${anstmp})"
-_DOMAIN_FQDN="${_ANSWER:-${anstmp}}"
+anstmp="17112018.fr.lxd 17112018.ovh.lxd ambau.fr.lxd ambau.ovh.lxd ggj.fr.lxd ggj.ovh.lxd han-sci.fr.lxd otokoz.ovh.lxd"
+[ "${_DOMAIN_FQDN%.lxd}" = "${_DOMAIN_FQDN}" ] && anstmp=${anstmp//.lxd/}
+_askno "All FQDN domains (${anstmp})"
+_DOMAIN_ALL_FQDN="${_ANSWER:-${anstmp}}"
+
+_menu "A principal fqdn domain (ambau.fr)" ${_DOMAIN_ALL_FQDN}
+_DOMAIN_FQDN="${_ANSWER}"
+
 _DOMAIN_NAME=${_DOMAIN_FQDN%.lxd} && _DOMAIN_NAME=${_DOMAIN_NAME%.*}
 _FILE_INSTALL_CONF=${S_PATH_CONF}/${_PART}-${_DOMAIN_FQDN}.conf
 _confset _FILE_INSTALL_CONF "${_FILE_INSTALL_CONF}" ${_FILE_INSTALL_CONF}
+_confset _DOMAIN_ALL_FQDN "${_DOMAIN_ALL_FQDN}" ${_FILE_INSTALL_CONF}
 _confset _DOMAIN_FQDN "${_DOMAIN_FQDN}" ${_FILE_INSTALL_CONF}
 _confset _DOMAIN_NAME "${_DOMAIN_NAME}" ${_FILE_INSTALL_CONF}
 
@@ -33,7 +40,7 @@ if ! _parthave ${_PARTMAIL} ${S_FILE_INSTALL_DONE}; then
 	[ "$_STEP" ] && _askno "Valid to continue" 
 else
 	. ${_FILE_INSTALL_CONF}
-	_echoW "performed *** ${_PARTMAIL}"
+	_echO "performed *** ${_PARTMAIL}"
 fi
 
 ####################  INIT
@@ -43,7 +50,7 @@ if ! _parthave ${_PARTMAIL} ${S_FILE_INSTALL_DONE}; then
 	. "${_PATH_BASE_SUB}/${_RELEASE_PART}-${_PARTMAIL}.install" || _exite "Wrong part: ${_PARTMAIL}"
 	[ "$_STEP" ] && _askno "Valid to continue" 
 else
-	_echoW "performed *** ${_PARTMAIL}"
+	_echO "performed *** ${_PARTMAIL}"
 fi
 
 ####################  SSL
@@ -53,7 +60,7 @@ if ! _parthave ${_PARTMAIL} ${S_FILE_INSTALL_DONE}; then
 	. "${_PATH_BASE_SUB}/${_RELEASE_PART}-${_PARTMAIL}.install" || _exite "Wrong part: ${_PARTMAIL}"
 	[ "$_STEP" ] && _askno "Valid to continue" 
 else
-	_echoW "performed *** ${_PARTMAIL}"
+	_echO "performed *** ${_PARTMAIL}"
 fi
 
 ####################  MARIADB
@@ -63,7 +70,7 @@ if ! _parthave ${_PARTMAIL} ${S_FILE_INSTALL_DONE}; then
 	. "${_PATH_BASE_SUB}/${_RELEASE_PART}-${_PARTMAIL}.install" || _exite "Wrong part: ${_PARTMAIL}"
 	[ "$_STEP" ] && _askno "Valid to continue" 
 else
-	_echoW "performed *** ${_PARTMAIL}"
+	_echO "performed *** ${_PARTMAIL}"
 fi
 
 ####################  _VMAIL_APP
@@ -73,7 +80,7 @@ if ! _parthave ${_PARTMAIL} ${S_FILE_INSTALL_DONE}; then
 	. "${_PATH_BASE_SUB}/${_RELEASE_PART}-${_PARTMAIL}.install" || _exite "Wrong part: ${_PARTMAIL}"
 	[ "$_STEP" ] && _askno "Valid to continue" 
 else
-	_echoW "performed *** ${_PARTMAIL}"
+	_echO "performed *** ${_PARTMAIL}"
 fi
 
 ####################  POSTFIX
@@ -83,7 +90,7 @@ if ! _parthave ${_PARTMAIL} ${S_FILE_INSTALL_DONE}; then
 	. "${_PATH_BASE_SUB}/${_RELEASE_PART}-${_PARTMAIL}.install" || _exite "Wrong part: ${_PARTMAIL}"
 	[ "$_STEP" ] && _askno "Valid to continue" 
 else
-	_echoW "performed *** ${_PARTMAIL}"
+	_echO "performed *** ${_PARTMAIL}"
 fi
 
 ####################  DOVECOT
@@ -93,12 +100,8 @@ if ! _parthave ${_PARTMAIL} ${S_FILE_INSTALL_DONE}; then
 	. "${_PATH_BASE_SUB}/${_RELEASE_PART}-${_PARTMAIL}.install" || _exite "Wrong part: ${_PARTMAIL}"
 	[ "$_STEP" ] && _askno "Valid to continue" 
 else
-	_echoW "performed *** ${_PARTMAIL}"
+	_echO "performed *** ${_PARTMAIL}"
 fi
-
-
-
-exit
 
 ####################  RSPAMD
 
@@ -107,19 +110,18 @@ if ! _parthave ${_PARTMAIL} ${S_FILE_INSTALL_DONE}; then
 	. "${_PATH_BASE_SUB}/${_RELEASE_PART}-${_PARTMAIL}.install" || _exite "Wrong part: ${_PARTMAIL}"
 	[ "$_STEP" ] && _askno "Valid to continue" 
 else
-	_echoW "performed *** ${_PARTMAIL}"
+	_echO "performed *** ${_PARTMAIL}"
 fi
 
 ####################  FAIL2BAN
 
-_PARTMAIL=mail-fail2ban
-if ! _parthave ${_PARTMAIL} ${S_FILE_INSTALL_DONE}; then
-	. "${_PATH_BASE_SUB}/${_RELEASE_PART}-${_PARTMAIL}.install" || _exite "Wrong part: ${_PARTMAIL}"
-	[ "$_STEP" ] && _askno "Valid to continue" 
-else
-	_echoW "performed *** ${_PARTMAIL}"
-fi
-
+#_PARTMAIL=mail-fail2ban
+#if ! _parthave ${_PARTMAIL} ${S_FILE_INSTALL_DONE}; then
+#	. "${_PATH_BASE_SUB}/${_RELEASE_PART}-${_PARTMAIL}.install" || _exite "Wrong part: ${_PARTMAIL}"
+#	[ "$_STEP" ] && _askno "Valid to continue" 
+#else
+#	_echO "performed *** ${_PARTMAIL}"
+#fi
 
 ########################  COPY
 
@@ -142,18 +144,10 @@ if ! lxc list -f json | jq -r '.[] | select(.name == "'${_CT_NAME}'").devices[].
 	_eval lxc config device override ${_CT_NAME} eth0 ipv4.address=${_CT_IP}
 fi
 
-
-########################  TEST
-
-_echot "------------------  mail test"
-
-
-
-
 ########################  HAPROXY
 
-_echoI "\nAdjust backend in proxy for backend: ${S_SERVICE[mail]} with:"
-_echo $(for i in `seq 1 ${_CT_NUM}`; do echo ${_CT_NAME}-${i};done)
+_echoA "Adjust backend in proxy for backend: ${S_SERVICE[mail]} with:"
+_echoa $(for i in `seq 1 ${_CT_NUM}`; do echo ${_CT_NAME}-${i};done)
 
 ########################  PUBLISH
 
