lxd-alpine: nearly finish haproxy

diff --git a/debian.install b/debian.install
--- a/debian.install
+++ b/debian.install
@@ -4,46 +4,49 @@
 
 <<MANUALY
 # HOME
-server=node2
+rm ~/.ssh/known_hosts
+server=node1 && ssh_port=2002
 
-cmds="apt update
-apt dist-upgrade
-apt install -y rsync zfsutils-linux
-ln -sv /usr/local/bs/conf/.bash_aliases /root/.bash_aliases"
+cmds="sudo  cp -a /root/.ssh/authorized_keys /root/.ssh/authorized_keys.$(date +%s)
+sudo sed -i 's|^no-port-forwarding.* \(ssh-rsa .*\)$|\1|' /root/.ssh/authorized_keys
+sudo sed -i 's|^#\?\(PermitRootLogin\) .*$|\1 without-password|' /etc/ssh/sshd_config
+sudo sed -i 's|^#\?\(Port\) .*$|\1 ${ssh_port}|' /etc/ssh/sshd_config
+echo '-------------- restart ssh' && sudo systemctl restart ssh.service"
 
-ssh root@${server} bash -i <<<$cmds
-rsync /home/shared/dev/bs/ root@${server}:/usr/local/bs/ -e 'ssh -p 22' --exclude=/.git --delete -av
-rsync /home/shared/dev/install/ root@${server}:/usr/local/bs/install/ -e 'ssh -p 22' --exclude=/.git --delete -av
+ssh ubuntu@${server} -p22 "${cmds}"
+
+rsync -e "ssh -p${ssh_port}" /home/shared/dev/bs/ root@${server}:/usr/local/bs/ --exclude=/.git* --delete -av && rsync -e "ssh -p${ssh_port}" /home/shared/dev/install/ root@${server}:/usr/local/install/ --exclude=/.git* --delete -av
 
 # HOST
-ssh root@${server}
+ssh root@${server} -p${ssh_port}
 
-/usr/local/bs/install/debian.install
+blkid|grep -v squashfs
+fdisk /dev/sda # m p F n w | extend with lxd:+50G / save:available
+blkid|grep -v squashfs
+
+apt update && apt -y dist-upgrade
+/usr/local/install/ubuntu.install
+# cp /usr/local/install/conf/server.conf-ovh /etc/server/server.conf
+# rsync -e "ssh -p${ssh_port}" /home/nikita/dev/install/conf/server.conf-ovh root@${server}:/etc/server/server.conf -av
 MANUALY
 
-################################ global functions
-#S_TRACE=debug
+################################ S_GLOBAL_FUNCTIONS
+S_TRACE=debug
 
-#allow conf-init
+# allow conf-init
 _INSTALL=debian
 
-if [[ -z "${S_GLOBAL_FUNCTIONS}" || -f ${S_GLOBAL_FUNCTIONS} ]]; then
-	file="/usr/local/bs/inc-functions.sh"
-	if ! . "${file}"; then echo -e "\e[1;31merror - unable to find file '${file}' from ${BASH_SOURCE[0]}\e[0;0m" && exit 1; fi
-fi
+S_GLOBAL_FUNCTIONS=${S_GLOBAL_FUNCTIONS:-/usr/local/bs/inc-functions.sh}
+! [ -f ${S_GLOBAL_FUNCTIONS} ] && echo -e "\e[1;31merror - unable to find file '${S_GLOBAL_FUNCTIONS}' from ${BASH_SOURCE[0]}\e[0;0m" && exit 1
 . ${S_GLOBAL_FUNCTIONS}
 
-################################  mandatory parts
 
-# init
-_PART="init"
-! _parthave "${_PART}" "${S_FILE_INSTALL_DONE}" && _source "${_PATH_BASE_SUB}/${S_RELEASE}-${_PART}.install"
-
+################################  MANDATORY
 
 # common + ssh
-parts="common ssh"
+parts="init common ssh"
 for _PART in $parts; do
-	! _parthave "${_PART}" "$S_FILE_INSTALL_DONE" && _source "${_PATH_BASE_SUB}/${S_RELEASE}-${_PART}.install"
+	! _parthave "${_PART}" "${S_FILE_INSTALL_DONE}" && _source "${_PATH_BASE_SUB}/${S_RELEASE}-${_PART}.install"
 done
 
 
@@ -51,8 +54,8 @@ done
 
 while [ "${_PART}" != "quit" ]; do
 
-	partsall="$(sed -n "s|^\t*\(\w\+\)) # .*$S_SERVER_TYPE.*$|\1|p" "$0" | xargs)"
-	partsrelease=" $(ls -1 "$_PATH_BASE_SUB"/*${S_RELEASE}* | sed -n "s|.*${S_RELEASE}-\(.*\)\.install|\1|p" | xargs) "
+	partsall="$(sed -n "s|^\t*\(\w\+\)) # .*${S_SERVER_TYPE}.*$|\1|p" "$0" | xargs)"
+	partsrelease=" $(ls -1 "${_PATH_BASE_SUB}"/*${S_RELEASE}* | sed -n "s|.*${S_RELEASE}-\(.*\)\.install|\1|p" | xargs) "
 	partsmade=" $(cat ${S_FILE_INSTALL_DONE} | xargs) "
 	parts2do=
 	for part in $partsall; do
diff --git a/lxd-alpine.install b/lxd-alpine.install
--- a/lxd-alpine.install
+++ b/lxd-alpine.install
@@ -5,11 +5,9 @@
 ################################ global functions
 S_TRACE=debug
 
-if [[ -z "$S_GLOBAL_FUNCTIONS" || -f $S_GLOBAL_FUNCTIONS ]]; then
-	file="/usr/local/bs/inc-functions.sh"
-	if ! . "$file"; then echo -e "\e[1;31merror - unable to find file '$file' from ${BASH_SOURCE[0]}\e[0;0m" && exit 1; fi
-fi
-. $S_GLOBAL_FUNCTIONS
+S_GLOBAL_FUNCTIONS=${S_GLOBAL_FUNCTIONS:-/usr/local/bs/inc-functions.sh}
+! [ -f ${S_GLOBAL_FUNCTIONS} ] && echo -e "\e[1;31merror - unable to find file '${S_GLOBAL_FUNCTIONS}' from ${BASH_SOURCE[0]}\e[0;0m" && exit 1
+. ${S_GLOBAL_FUNCTIONS}
 
 
 ################################  conf
@@ -24,7 +22,7 @@ S_PATH_INSTALL_CONF="${S_PATH_INSTALL}/conf"
 S_FILE_INSTALL_CONF="${S_PATH_CONF}/lxd.conf"
 S_FILE_INSTALL_DONE="${S_PATH_CONF}/lxd.done"
 
-[ -f "$S_FILE_INSTALL_CONF" ] && . "$S_FILE_INSTALL_CONF"
+[ -f "${S_FILE_INSTALL_CONF}" ] && . "${S_FILE_INSTALL_CONF}"
 
 #don't mix with S_* variables
 [ -z ${_RELEASE_ID+x} ] && _RELEASE_ID="alpine" && _confset _RELEASE_ID "${_RELEASE_ID}"
diff --git a/ubuntu.install b/ubuntu.install
--- a/ubuntu.install
+++ b/ubuntu.install
@@ -30,19 +30,18 @@ apt update && apt -y dist-upgrade
 # rsync -e "ssh -p${ssh_port}" /home/nikita/dev/install/conf/server.conf-ovh root@${server}:/etc/server/server.conf -av
 MANUALY
 
-################################ global functions
+################################ S_GLOBAL_FUNCTIONS
 S_TRACE=debug
 
 # allow conf-init
 _INSTALL=ubuntu
 
-if [[ -z "${S_GLOBAL_FUNCTIONS}" || -f ${S_GLOBAL_FUNCTIONS} ]]; then
-	S_GLOBAL_FUNCTIONS="/usr/local/bs/inc-functions.sh"
-	if ! . "${S_GLOBAL_FUNCTIONS}"; then echo -e "\e[1;31merror - unable to find file '${S_GLOBAL_FUNCTIONS}' from ${BASH_SOURCE[0]}\e[0;0m" && exit 1; fi
-fi
+S_GLOBAL_FUNCTIONS=${S_GLOBAL_FUNCTIONS:-/usr/local/bs/inc-functions.sh}
+! [ -f ${S_GLOBAL_FUNCTIONS} ] && echo -e "\e[1;31merror - unable to find file '${S_GLOBAL_FUNCTIONS}' from ${BASH_SOURCE[0]}\e[0;0m" && exit 1
 . ${S_GLOBAL_FUNCTIONS}
 
-################################  mandatory parts
+
+################################  MANDATORY
 
 # common + ssh
 parts="init common ssh"
