lxd-alpine-mariadb-ms: - rename lxd-alpine-mariadb-dom to lxd-alpine-mariadb-ms - stabilized version of lxd-alpine-mariadb-ms - global change of calling _partadd

diff --git a/sub/lxd-alpine-apache.install b/sub/lxd-alpine-apache.install
--- a/sub/lxd-alpine-apache.install
+++ b/sub/lxd-alpine-apache.install
@@ -4,20 +4,21 @@
 
 _echoT "\n==========================================  ${_RELEASE} ${_PART}"
 
+grep -q "^# ${_PART}$" ${S_FILE_INSTALL_CONF} || echo  "# ${_PART}" | _evalqr tee -a ${S_FILE_INSTALL_CONF}
 
 ########################  REQUIRED
 
 _echoT "------------------ required vm image"
-lxc image list -f json |jq -r '.[].aliases[].name' | grep -q ^${_CT_NAME_COM}$ || _exite "Unable to find image container: '${_CT_NAME_COM}'"
+lxc image list -f csv -c l | grep -q ^${_CT_NAME_COM}$ || _exite "Unable to find image container: '${_CT_NAME_COM}'"
 
 _echoT "------------------ required vm"
-lxc list -f json |jq -r '.[].name'| grep -q ^${S_SERVICE[log]}$ || _exite "Unable to find image container: '${S_SERVICE[log]}'"
+lxc list -f csv -c n | grep -q ^${S_SERVICE[log]}$ || _exite "Unable to find image container: '${S_SERVICE[log]}'"
 
+file_site=${S_PATH_INSTALL_CONF}/apache2/default.conf
 file_rsyslog_host=${S_PATH_INSTALL_CONF}/rsyslog/host-apache.conf
 file_rsyslog_client=${S_PATH_INSTALL_CONF}/rsyslog/client-apache.conf
 file_logrotate_host=${S_PATH_INSTALL_CONF}/logrotate/host-apache
 file_log=${S_PATH_INSTALL_CONF}/apache2/log.conf
-file_site=${S_PATH_INSTALL_CONF}/apache2/default.conf
 
 _echoT "------------------ required files"
 _require ${file_rsyslog_host} ${file_rsyslog_client} ${file_logrotate_host} ${file_log} ${file_site}
@@ -40,42 +41,42 @@ file_conf_http=/etc/apache2/httpd.conf
 
 _echoT "----------  data sysctl.conf"
 
-[ -z ${_APA_MAX_SYN_BACKLOG+x} ] && anstmp="${_MAX_SYN_BACKLOG}" && _askno "Set $(sysctl net.ipv4.tcp_max_syn_backlog) - (${anstmp})" && _APA_MAX_SYN_BACKLOG=${_ANSWER:-$anstmp} && _confset _APA_MAX_SYN_BACKLOG "${_APA_MAX_SYN_BACKLOG}"
+[ -z ${_APA_MAX_SYN_BACKLOG+x} ] && anstmp="${_MAX_SYN_BACKLOG}" && _askno "Set $(sysctl net.ipv4.tcp_max_syn_backlog) - (${anstmp})" && _APA_MAX_SYN_BACKLOG="${_ANSWER:-$anstmp}" && _confset _APA_MAX_SYN_BACKLOG "${_APA_MAX_SYN_BACKLOG}"
 
-[ -z ${_APA_MAX_TW_BUCKETS+x} ] && anstmp="${_MAX_TW_BUCKETS}" && _askno "Set $(sysctl net.ipv4.tcp_max_tw_buckets) - (${anstmp})" && _APA_MAX_TW_BUCKETS=${_ANSWER:-$anstmp} && _confset _APA_MAX_TW_BUCKETS "${_APA_MAX_TW_BUCKETS}"
+[ -z ${_APA_MAX_TW_BUCKETS+x} ] && anstmp="${_MAX_TW_BUCKETS}" && _askno "Set $(sysctl net.ipv4.tcp_max_tw_buckets) - (${anstmp})" && _APA_MAX_TW_BUCKETS="${_ANSWER:-$anstmp}" && _confset _APA_MAX_TW_BUCKETS "${_APA_MAX_TW_BUCKETS}"
 
-[ -z ${_APA_FIN_TIMEOUT+x} ] && anstmp="${_FIN_TIMEOUT}" && _askno "Set $(sysctl net.ipv4.tcp_fin_timeout) - (${anstmp})" && _APA_FIN_TIMEOUT=${_ANSWER:-$anstmp} && _confset _APA_FIN_TIMEOUT "${_APA_FIN_TIMEOUT}"
+[ -z ${_APA_FIN_TIMEOUT+x} ] && anstmp="${_FIN_TIMEOUT}" && _askno "Set $(sysctl net.ipv4.tcp_fin_timeout) - (${anstmp})" && _APA_FIN_TIMEOUT="${_ANSWER:-$anstmp}" && _confset _APA_FIN_TIMEOUT "${_APA_FIN_TIMEOUT}"
 
-[ -z ${_APA_KEEPALIVE_TIME+x} ] && anstmp="240" && _askno "Set $(sysctl net.ipv4.tcp_keepalive_time) - (${anstmp})" && _APA_KEEPALIVE_TIME=${_ANSWER:-$anstmp} && _confset _APA_KEEPALIVE_TIME "${_APA_KEEPALIVE_TIME}"
+[ -z ${_APA_KEEPALIVE_TIME+x} ] && anstmp="240" && _askno "Set $(sysctl net.ipv4.tcp_keepalive_time) - (${anstmp})" && _APA_KEEPALIVE_TIME="${_ANSWER:-$anstmp}" && _confset _APA_KEEPALIVE_TIME "${_APA_KEEPALIVE_TIME}"
 
-[ -z ${_APA_KEEPALIVE_INTVL+x} ] && anstmp="30" && _askno "Set $(sysctl net.ipv4.tcp_keepalive_intvl) - (${anstmp})" && _APA_KEEPALIVE_INTVL=${_ANSWER:-$anstmp} && _confset _APA_KEEPALIVE_INTVL "${_APA_KEEPALIVE_INTVL}"
+[ -z ${_APA_KEEPALIVE_INTVL+x} ] && anstmp="30" && _askno "Set $(sysctl net.ipv4.tcp_keepalive_intvl) - (${anstmp})" && _APA_KEEPALIVE_INTVL="${_ANSWER:-$anstmp}" && _confset _APA_KEEPALIVE_INTVL "${_APA_KEEPALIVE_INTVL}"
 
-[ -z ${_APA_KEEPALIVE_PROBES+x} ] && anstmp="9" && _askno "Set $(sysctl net.ipv4.tcp_keepalive_probes) - (${anstmp})" && _APA_KEEPALIVE_PROBES=${_ANSWER:-$anstmp} && _confset _APA_KEEPALIVE_PROBES "${_APA_KEEPALIVE_PROBES}"
+[ -z ${_APA_KEEPALIVE_PROBES+x} ] && anstmp="9" && _askno "Set $(sysctl net.ipv4.tcp_keepalive_probes) - (${anstmp})" && _APA_KEEPALIVE_PROBES="${_ANSWER:-$anstmp}" && _confset _APA_KEEPALIVE_PROBES "${_APA_KEEPALIVE_PROBES}"
 
 
 _echoT "----------  data apache"
 
-[ -z ${_APA_TIMEOUT+x} ] && anstmp="60" && _askno "Time before receives and sends time out (${anstmp})" && _APA_TIMEOUT=${_ANSWER:-$anstmp} && _confset _APA_TIMEOUT "${_APA_TIMEOUT}"
+[ -z ${_APA_TIMEOUT+x} ] && anstmp="60" && _askno "Time before receives and sends time out (${anstmp})" && _APA_TIMEOUT="${_ANSWER:-$anstmp}" && _confset _APA_TIMEOUT "${_APA_TIMEOUT}"
 
-[ -z ${_APA_KEEPALIVE+x} ] && anstmp="On" && _askno "Allow persistent connections On/Off (${anstmp})" && _APA_KEEPALIVE=${_ANSWER:-$anstmp} && _confset _APA_KEEPALIVE "${_APA_KEEPALIVE}"
+[ -z ${_APA_KEEPALIVE+x} ] && anstmp="On" && _askno "Allow persistent connections On/Off (${anstmp})" && _APA_KEEPALIVE="${_ANSWER:-$anstmp}" && _confset _APA_KEEPALIVE "${_APA_KEEPALIVE}"
 
-[ -z ${_APA_KEEPALIVE_REQUEST+x} ] && anstmp="100" && _askno "The maximum number of requests to allow during a persistent connection (${anstmp})" && _APA_KEEPALIVE_REQUEST=${_ANSWER:-$anstmp} && _confset _APA_KEEPALIVE_REQUEST "${_APA_KEEPALIVE_REQUEST}"
+[ -z ${_APA_KEEPALIVE_REQUEST+x} ] && anstmp="100" && _askno "The maximum number of requests to allow during a persistent connection (${anstmp})" && _APA_KEEPALIVE_REQUEST="${_ANSWER:-$anstmp}" && _confset _APA_KEEPALIVE_REQUEST "${_APA_KEEPALIVE_REQUEST}"
 
- [ -z ${_APA_KEEPALIVE_TIMEOUT+x} ] && anstmp="5" && _askno "Number of seconds to wait for the next request (${anstmp})" && _APA_KEEPALIVE_TIMEOUT=${_ANSWER:-$anstmp} && _confset _APA_KEEPALIVE_TIMEOUT "${_APA_KEEPALIVE_TIMEOUT}"
+ [ -z ${_APA_KEEPALIVE_TIMEOUT+x} ] && anstmp="5" && _askno "Number of seconds to wait for the next request (${anstmp})" && _APA_KEEPALIVE_TIMEOUT="${_ANSWER:-$anstmp}" && _confset _APA_KEEPALIVE_TIMEOUT "${_APA_KEEPALIVE_TIMEOUT}"
 
 _echoT "----------  data apache mpm"
 
-[ -z ${_APA_START_SERVERS+x} ] && anstmp="13" && _askno "StartServers (${anstmp})" && _APA_START_SERVERS=${_ANSWER:-$anstmp} && _confset _APA_START_SERVERS "${_APA_START_SERVERS}"
+[ -z ${_APA_START_SERVERS+x} ] && anstmp="13" && _askno "StartServers (${anstmp})" && _APA_START_SERVERS="${_ANSWER:-$anstmp}" && _confset _APA_START_SERVERS "${_APA_START_SERVERS}"
 
-[ -z ${_APA_MIN_SPARE_THREADS+x} ] && anstmp="50" && _askno "MinSpareThreads (${anstmp})" && _APA_MIN_SPARE_THREADS=${_ANSWER:-$anstmp} && _confset _APA_MIN_SPARE_THREADS "${_APA_MIN_SPARE_THREADS}"
+[ -z ${_APA_MIN_SPARE_THREADS+x} ] && anstmp="50" && _askno "MinSpareThreads (${anstmp})" && _APA_MIN_SPARE_THREADS="${_ANSWER:-$anstmp}" && _confset _APA_MIN_SPARE_THREADS "${_APA_MIN_SPARE_THREADS}"
 
-[ -z ${_APA_MAX_SPARE_THREADS+x} ] && anstmp="250" && _askno "MaxSpareThreads (${anstmp})" && _APA_MAX_SPARE_THREADS=${_ANSWER:-$anstmp} && _confset _APA_MAX_SPARE_THREADS "${_APA_MAX_SPARE_THREADS}"
+[ -z ${_APA_MAX_SPARE_THREADS+x} ] && anstmp="250" && _askno "MaxSpareThreads (${anstmp})" && _APA_MAX_SPARE_THREADS="${_ANSWER:-$anstmp}" && _confset _APA_MAX_SPARE_THREADS "${_APA_MAX_SPARE_THREADS}"
 
- [ -z ${_APA_THREADS_PER_CHILD+x} ] && anstmp="25" && _askno "ThreadsPerChild (${anstmp})" && _APA_THREADS_PER_CHILD=${_ANSWER:-$anstmp} && _confset _APA_THREADS_PER_CHILD "${_APA_THREADS_PER_CHILD}"
+ [ -z ${_APA_THREADS_PER_CHILD+x} ] && anstmp="25" && _askno "ThreadsPerChild (${anstmp})" && _APA_THREADS_PER_CHILD="${_ANSWER:-$anstmp}" && _confset _APA_THREADS_PER_CHILD "${_APA_THREADS_PER_CHILD}"
 
- [ -z ${_APA_MAX_REQUEST_WORKERS+x} ] && anstmp="400" && _askno "MaxRequestWorkers (${anstmp})" && _APA_MAX_REQUEST_WORKERS=${_ANSWER:-$anstmp} && _confset _APA_MAX_REQUEST_WORKERS "${_APA_MAX_REQUEST_WORKERS}"
+ [ -z ${_APA_MAX_REQUEST_WORKERS+x} ] && anstmp="400" && _askno "MaxRequestWorkers (${anstmp})" && _APA_MAX_REQUEST_WORKERS="${_ANSWER:-$anstmp}" && _confset _APA_MAX_REQUEST_WORKERS "${_APA_MAX_REQUEST_WORKERS}"
 
- [ -z ${_APA_MAX_CONNECTIONS_PER_CHILD+x} ] && anstmp="0" && _askno "MaxConnectionsPerChild (${anstmp})" && _APA_MAX_CONNECTIONS_PER_CHILD=${_ANSWER:-$anstmp} && _confset _APA_MAX_CONNECTIONS_PER_CHILD "${_APA_MAX_CONNECTIONS_PER_CHILD}"
+ [ -z ${_APA_MAX_CONNECTIONS_PER_CHILD+x} ] && anstmp="0" && _askno "MaxConnectionsPerChild (${anstmp})" && _APA_MAX_CONNECTIONS_PER_CHILD="${_ANSWER:-$anstmp}" && _confset _APA_MAX_CONNECTIONS_PER_CHILD "${_APA_MAX_CONNECTIONS_PER_CHILD}"
 
 
 ########################  PROFILE
@@ -88,7 +89,7 @@ _eval lxc profile create ${profile}
 
 path=${S_HOST_PATH_SHARE}/www/${S_DOMAIN_FQDN}
 path_ct=${_APA_PATH_DOMAIN}
-[ -d ${path} ] || _eval mkdir -p ${path}
+[ -d ${path} ] || _evalr mkdir -p ${path}
 _eval lxc profile device add ${profile} ${profile} disk source=${path} path=${path_ct}
 
 
@@ -96,8 +97,8 @@ _eval lxc profile device add ${profile} ${profile} disk source=${path} path=${pa
 
 _echoT "----------  init"
 
-if lxc list -f json |jq -r '.[].name' | grep -q ^${_CT_NAME}$; then
-	if lxc list -f json | jq -r '.[] | select(.status == "Running").name' | grep -q ^${_CT_NAME}$; then
+if lxc list -f csv -c n | grep -q ^${_CT_NAME}$; then
+	if lxc list -f csv -c n status=Running| grep -q ^${_CT_NAME}$; then
 		_eval lxc stop ${_CT_NAME}
 		_eval lxc rename ${_CT_NAME} ${_CT_NAME}-${_SDATE}
 		_eval lxc start ${_CT_NAME}-${_SDATE}
@@ -118,10 +119,7 @@ _eval lxc init ${_CT_NAME_COM} ${_CT_NAME} -p default -p global -p ${profile}
 
 
 _echoT "----------  ${_CT_NAME} start"
-
 _eval lxc start ${_CT_NAME}
-
-_eval sleep 1
 
 
 ########################  SYSCTL
@@ -163,7 +161,7 @@ _lxc_exec ${_CT_NAME} "rc-service ${service} start"
 
 _echoT "----------  conf.d default"
 
-file=/etc/apache2/conf.d/default.conf
+file=${file_site}/etc/apache2/conf.d/default.conf
 _lxc_exec ${_CT_NAME} "[ -f ${file} ] && cp -a ${file} ${file}.${_SDATE}"
 
 cmds="sed -i 's|^.\?\(Timeout\) .*$|\1 ${_APA_TIMEOUT}|' ${file}
@@ -226,10 +224,11 @@ _lxc_exec ${_CT_NAME} "sed -i '/^<Directory \"\/var\/www\/localhost\/html\">/,/<
 # Log options
 _lxc_exec ${_CT_NAME} "sed -i '/^LogLevel/ s|^|#|' ${file_conf_http}"
 _lxc_exec ${_CT_NAME} "sed -i '/^ErrorLog/ s|^|#|' ${file_conf_http}"
-_lxc_exec ${_CT_NAME} "sed -i '/^<IfModule log_config_module>/,/^<\/IfModule>/ s|^|#|' ${file_conf_http}"
+_lxc_exec ${_CT_NAME} "sed -i '/^<IfModule log_config_module>/i# To configure logs, see the file: ${path_conf}/log.conf' ${file_conf_http}"
+#_lxc_exec ${_CT_NAME} "sed -i '/^<IfModule log_config_module>/,/^<\/IfModule>/ s|^\([^<].*\)$|#\1|' ${file_conf_http}"
 
 file=/etc/apache2/conf.d/${file_log##*/}
-_eval lxc file push ${file_log} ${_CT_NAME}/${file}
+_eval lxc file push ${file_log} ${_CT_NAME}${file}
 _lxc_var_replace ${_CT_NAME} ${file} apache
 
 
@@ -273,7 +272,7 @@ _lxc_exec ${_CT_NAME} "echo '<html><body><h1>${S_DOMAIN_FQDN} works!</h1></body>
 _echoT "----------  ${S_DOMAIN_FQDN} conf"
 
 file=${path_sites}/${file_site##*/}
-_eval lxc file push ${file_site} ${_CT_NAME}/${file}
+_eval lxc file push ${file_site} ${_CT_NAME}${file}
 _lxc_var_replace ${_CT_NAME} ${file} apache
 
 
@@ -361,7 +360,7 @@ _lxc_exec ${_CT_NAME} "find ${S_PATH_LOG}/apache2 -name *.log -exec rm {} \;"
 
 _echoT "----------  publish ${_CT_NAME}"
 
-_eval lxc image list -f json | jq -r '.[].aliases[].name' | grep -q ^${_CT_NAME}$ && lxc image alias rename ${_CT_NAME} ${_CT_NAME}-$(date +%s)
+_eval lxc image list -f csv -c l | grep -q ^${_CT_NAME}$ && lxc image alias rename ${_CT_NAME} ${_CT_NAME}-$(date +%s)
 _eval lxc publish --force ${_CT_NAME} --alias ${_CT_NAME}
 
 
@@ -376,8 +375,8 @@ _echo "curl ${_CT_NAME}/ping-monitor"
 
 ########################  END
 
-_echoT "---------- ${_PART} end"
-_eval "_partadd ${_PART} ${S_FILE_INSTALL_DONE}"
+_echoT "===================== ${_PART} end"
+_partadd ${_PART} ${S_FILE_INSTALL_DONE}
 
 
 <<KEEP
diff --git a/sub/lxd-alpine-haproxy.install b/sub/lxd-alpine-haproxy.install
--- a/sub/lxd-alpine-haproxy.install
+++ b/sub/lxd-alpine-haproxy.install
@@ -4,15 +4,16 @@
 
 _echoT "\n==========================================  ${_RELEASE} ${_PART}"
 
+grep -q "^# ${_PART}$" ${S_FILE_INSTALL_CONF} || echo  "# ${_PART}" | _evalqr tee -a ${S_FILE_INSTALL_CONF}
 
 ########################  REQUIRED
 
 _echoT "------------------ required vm image"
-lxc image list -f json |jq -r '.[].aliases[].name' | grep -q ^${_CT_NAME_COM}$ || _exite "Unable to find image container: '${_CT_NAME_COM}'"
+lxc image list -f csv -c l | grep -q ^${_CT_NAME_COM}$ || _exite "Unable to find image container: '${_CT_NAME_COM}'"
 
 _echoT "------------------ required vm"
-lxc list -f json |jq -r '.[].name'| grep -q ^${S_SERVICE[log]}$ || _exite "Unable to find image container: '${S_SERVICE[log]}'"
-lxc list -f json |jq -r '.[].name'| grep -q ^${S_SERVICE[http]}$ || _exite "Unable to find image container: '${S_SERVICE[http]}'"
+lxc list -f csv -c n | grep -q ^${S_SERVICE[log]}$ || _exite "Unable to find image container: '${S_SERVICE[log]}'"
+lxc list -f csv -c n | grep -q ^${S_SERVICE[http]}$ || _exite "Unable to find image container: '${S_SERVICE[http]}'"
 
 file_haproxy_initd=${S_PATH_INSTALL_XTRA}/haproxy
 file_vim=${S_PATH_SCRIPT_CONF}/.vimrc
@@ -54,8 +55,8 @@ _HPX_DOMAIN_2_NAME="${_HPX_DOMAIN_2_FQDN%.*}" && _confset _HPX_DOMAIN_2_NAME "${
 
 _echoT "----------  init"
 
-if lxc list -f json |jq -r '.[].name' | grep -q ^${_CT_NAME}$; then
-	if lxc list -f json | jq -r '.[] | select(.status == "Running").name' | grep -q ^${_CT_NAME}$; then
+if lxc list -f csv -c n | grep -q ^${_CT_NAME}$; then
+	if lxc list -f csv -c n status=Running| grep -q ^${_CT_NAME}$; then
 		_eval lxc stop ${_CT_NAME}
 		_eval lxc rename ${_CT_NAME} ${_CT_NAME}-${_SDATE}
 		_eval lxc start ${_CT_NAME}-${_SDATE}
@@ -76,10 +77,7 @@ _eval lxc config device set ${_CT_NAME} eth0 ipv4.address ${_CT_IP}
 
 
 _echoT "----------  ${_CT_NAME} start"
-
 _eval lxc start ${_CT_NAME}
-
-_eval sleep 1
 
 
 ########################  SYSCTL
@@ -152,7 +150,7 @@ done
 
 _echoT "----------  conf init.d"
 
-file=/etc/init.d/haproxy
+file=/etc/init.d/${file_haproxy_initd##*/}
 _lxc_exec ${_CT_NAME} "[ -f ${file} ] && mv ${file} ${file}.${_SDATE} && chmod -x ${file}.${_SDATE}"
 _eval lxc file push ${file_haproxy_initd} ${_CT_NAME}/etc/init.d/haproxy
 _lxc_exec ${_CT_NAME} "chmod +x ${file}"
@@ -242,7 +240,7 @@ _lxc_var_replace ${S_SERVICE[log]} ${file} logrotate
 
 _echoT "----------  publish ${_CT_NAME}"
 
-_eval lxc image list -f json | jq -r '.[].aliases[].name' | grep -q ^${_CT_NAME}$ && lxc image alias rename ${_CT_NAME} ${_CT_NAME}-$(date +%s)
+_eval lxc image list -f csv -c l | grep -q ^${_CT_NAME}$ && lxc image alias rename ${_CT_NAME} ${_CT_NAME}-$(date +%s)
 _eval lxc publish --force ${_CT_NAME} --alias ${_CT_NAME}
 
 
@@ -251,7 +249,7 @@ _eval lxc publish --force ${_CT_NAME} --alias ${_CT_NAME}
 _echoT "----------  test haproxy"
 
 _echoI "password to access to  haproxy: ${_HPX_ACCESS_PWD}"
-_echoW "{_IPTHIS}:${S_HAPROXY_STATS_PORT}${_HPX_ACCESS_URI}"
+_echoW "${_IPTHIS}:${S_HAPROXY_STATS_PORT}${_HPX_ACCESS_URI}"
 
 _echoT "----------  test ${_CT_NAME}"
 
@@ -262,5 +260,5 @@ _echo "curl ${S_DOMAIN_FQDN}:80"
 
 ########################  END
 
-_echoT "---------- ${_PART} end"
-_eval "_partadd ${_PART} ${S_FILE_INSTALL_DONE}"
+_echoT "===================== ${_PART} end"
+_partadd ${_PART} ${S_FILE_INSTALL_DONE}
diff --git a/sub/lxd-alpine-mariadb.install b/sub/lxd-alpine-mariadb.install
--- a/sub/lxd-alpine-mariadb.install
+++ b/sub/lxd-alpine-mariadb.install
@@ -4,51 +4,54 @@
 
 _echoT "\n==========================================  ${_RELEASE} ${_PART}"
 
+grep -q "^# ${_PART}$" ${S_FILE_INSTALL_CONF} || echo  "# ${_PART}" | _evalqr tee -a ${S_FILE_INSTALL_CONF}
 
 ########################  REQUIRED
 
 _echoT "------------------ required vm image"
-lxc image list -f json |jq -r '.[].aliases[].name' | grep -q ^${_CT_NAME_COM}$ || _exite "Unable to find image container: '${_CT_NAME_COM}"
+lxc image list -f csv -c l | grep -q ^${_CT_NAME_COM}$ || _exite "Unable to find image container: '${_CT_NAME_COM}"
 
 _echoT "------------------ required vm"
-lxc list -f json |jq -r '.[].name'| grep -q ^${S_SERVICE[log]}$ || _exite "Unable to find image container: '${S_SERVICE[log]}'"
+lxc list -f csv -c n| grep -q ^${S_SERVICE[log]}$ || _exite "Unable to find image container: '${S_SERVICE[log]}'"
 
-
-file_server="${S_PATH_INSTALL_CONF}/mariadb/mariadb-server.conf"
-file_master="${S_PATH_INSTALL_CONF}/mariadb/mariadb-master.conf"
+file_server="${S_PATH_INSTALL_CONF}/mariadb/mariadb-server.cnf"
 file_rsyslog_client=${S_PATH_INSTALL_CONF}/rsyslog/client-mariadb.conf
 file_rsyslog_host=${S_PATH_INSTALL_CONF}/rsyslog/host-mariadb.conf
 file_logrotate_client=${S_PATH_INSTALL_CONF}/logrotate/host-mariadb
 file_logrotate_host=${S_PATH_INSTALL_CONF}/logrotate/host-mariadb
 
 _echoT "------------------ required files"
-_require ${file_server} ${file_master} ${file_rsyslog_client} ${file_rsyslog_host} ${file_logrotate_client} ${file_logrotate_host}
+_require ${file_server} ${file_rsyslog_client} ${file_rsyslog_host} ${file_logrotate_client} ${file_logrotate_host}
 
 
 ########################  DATA
 
-_CT_NAME=${S_SERVICE[sgbd]}
-
-eval ${S_HOST_VM_ETH[default]}
-#_CT_IP=${s_base}.${S_SERVICE_BITS[maria]}
-
-_MDB_SERVICE=mariadb && _confset _MDB_SERVICE "${_MDB_SERVICE}"
-_MDB_HOST_PATH=${S_HOST_PATH}/mariadb/mariadb-${S_DOMAIN_FQDN} && _confset _MDB_HOST_PATH "${_MDB_HOST_PATH}"
-_MDB_VM_PATH=/var/lib/mysql && _confset _MDB_VM_PATH "${_MDB_VM_PATH}"
-
-path_conf=/etc/my.cnf.d
-_MDB_PATH_LOG=${S_PATH_LOG}/mysql
-
-
 _echoT "----------  data pwd"
 
-[ -z ${_MDB_PWD_LOCAL+x} ] && pwdtmp=`_pwd` && _askno "Enter a password for 'root@localhost ($pwdtmp)" && _MDB_PWD_LOCAL=${_ANSWER:-$pwdtmp} && _confset _MDB_PWD_LOCAL "${_MDB_PWD_LOCAL}"
+_MDB_PWD_LOCAL=`_pwd`
+_MDB_PWD_ADMIN=`_pwd`
+_MDB_PWD_HOST=`_pwd`
+_MDB_PWD_REMOTE=`_pwd`
 
-[ -z ${_MDB_PWD_ADMIN+x} ] && pwdtmp=`_pwd` && _askno "Enter a password for 'rootadmin@${S_SERVICE[admin]}' ($pwdtmp)" && _MDB_PWD_ADMIN=${_ANSWER:-$pwdtmp} && _confset _MDB_PWD_ADMIN "${_MDB_PWD_ADMIN}"
 
-[ -z ${_MDB_PWD_HOST+x} ] && pwdtmp=`_pwd` && _askno "Enter a password for 'roothost@${_IPS_CLUSTER}' ($pwdtmp)" && _MDB_PWD_HOST=${_ANSWER:-$pwdtmp} && _confset _MDB_PWD_HOST "${_MDB_PWD_HOST}"
+_echoT "----------  data"
 
-[ -z ${_MDB_PWD_REMOTE+x} ] && pwdtmp=`_pwd` && _askno "Enter a password for 'rootremote@${S_IPS_ADMIN}' ($pwdtmp)" && _MDB_PWD_REMOTE=${_ANSWER:-$pwdtmp} && _confset _MDB_PWD_REMOTE "${_MDB_PWD_REMOTE}"
+_MDB_SERVICE=mariadb && _confset _MDB_SERVICE "${_MDB_SERVICE}"
+_MDB_PATH_CONF=/etc/my.cnf.d && _confset _MDB_PATH_CONF "${_MDB_PATH_CONF}"
+
+anstmp=maria-srv && _askno "Name of the container profile ($anstmp)" && _MDB_NAME="${_ANSWER:-$anstmp}"
+
+[ ${_MDB_NAME} = maria-srv ] && anstmp=${S_SERVICE[sgbd]} || anstmp=${_MDB_NAME//./-}
+_askno "Name of the container ($anstmp)" && _CT_NAME="${_ANSWER:-$anstmp}"
+
+[ -z ${_MDB_VM_PATH+x} ] && anstmp=/var/lib/mysql && _askno "Path for data (${anstmp})" && _MDB_VM_PATH="${_ANSWER:-$anstmp}" && _confset _MDB_VM_PATH "${_MDB_VM_PATH}"
+
+[ -z ${_MDB_PATH_BINLOG+x} ] && anstmp=/var/lib/mysql && _askno "Path for binary logs (${anstmp})" && _MDB_PATH_BINLOG="${_ANSWER:-$anstmp}" && _confset _MDB_PATH_BINLOG "${_MDB_PATH_BINLOG}"
+
+[ -z ${_MDB_PATH_LOG+x} ] && anstmp=${S_PATH_LOG}/mysql && _askno "Path for logs (${anstmp})" && _MDB_PATH_LOG="${_ANSWER:-$anstmp}" && _confset _MDB_PATH_LOG "${_MDB_PATH_LOG}"
+
+
+_MDB_HOST_PATH=${S_HOST_PATH}/mariadb/${_MDB_NAME} && _confset _MDB_HOST_PATH "${_MDB_HOST_PATH}"
 
 
 ########################  STORAGE MARIADB
@@ -57,38 +60,61 @@ if [ "${S_STORAGE_DRIVER}" = zfs ]; then
 
 	name=mariadb
 	_echoT "----------  zfs ${name}"
-
 	path_zfs=${_ZFS_ROOT}${S_HOST_PATH}/mariadb
 	path=${S_HOST_PATH}/mariadb
 	opts="-o mountpoint=${path} -o compression=lz4 -o  acltype=posixacl -o recordsize=8K -o primarycache=metadata"
 	cmd="zfs create ${opts} ${path_zfs}"
-	zfs list ${path_zfs} >/dev/null 2>&1 || _eval ${cmd}
+	_evalr zfs list ${path_zfs} >/dev/null 2>&1 || _evalr ${cmd}
 
 
-	name=mariadb-${S_DOMAIN_FQDN}
+	name=${_MDB_NAME}
 	_echoT "----------  zfs ${name}"
-
 	path_zfs=${_ZFS_ROOT}${_MDB_HOST_PATH}
 	path=${_MDB_HOST_PATH}
 
 	# rename
 	if zfs list ${path_zfs} >/dev/null 2>&1; then
 	 	_echoT "----------  unmount  ${path_zfs}"
-	 	zfs unmount ${path_zfs} || _exite "Unable to unmount ${path_zfs}\nUnbind container using it"
+	 	_evalr zfs unmount ${path_zfs} || _exite "Unable to unmount ${path_zfs}\nUnbind container using it"
 
-		_echoT "----------  zfs backup ${path_zfs} to ${path_zfs}.${_SDATE}"
-	 	_eval zfs rename ${path_zfs} ${path_zfs}.${_SDATE}
+		_echoI "----------  zfs backup ${path_zfs} to ${path_zfs}.${_SDATE}"
+	 	_evalr zfs rename ${path_zfs} ${path_zfs}.${_SDATE}
 	 fi
 
 	_echoT "----------  zfs create ${path_zfs}"
-	_eval zfs create -o mountpoint=${path} ${path_zfs}
+	_evalr zfs create -o mountpoint=${path} ${path_zfs}
 
 	_echoT "----------  rights ${name}"
 
-	_eval chown 1000100:1000101 ${path}
+	_evalr chown 1000100:1000101 ${path}
+	_evalr setfacl -Rm u:1000000:rwx ${path}
+	_evalr setfacl -Rm d:u:1000000:rwx ${path}
 
-	_eval setfacl -Rm u:1000000:rwx ${path}
-	_eval setfacl -Rm d:u:1000000:rwx ${path}
+elif [ "${S_STORAGE_DRIVER}" = btrfs ]; then
+
+	name=mariadb
+	_echoT "----------  btrfs ${name}"
+	path_base=${S_HOST_PATH}
+	_evalr ls -1 ${path_base} | grep -q ${name}$ || _evalr btrfs subvolume create ${path_base}/${name}
+
+	name=${_MDB_NAME}
+	_echoT "----------  btrfs ${name}"
+	# rename
+	path_base=${S_HOST_PATH}/mariadb
+	path=${_MDB_HOST_PATH}
+	if _evalr ls -1 ${path_base} | grep -q ${name}$; then
+		_echoI "----------  mv ${path} to ${path}.${_SDATE}"
+	 	_evalr mv ${path} ${path}.${_SDATE}
+	 fi
+
+	_echoT "----------  btrfs create ${path}"
+	_evalr btrfs subvolume create ${path}
+
+	_echoT "----------  rights ${name}"
+
+	_evalr chown 100100:100101 ${path}
+	_evalr setfacl -Rm u:100000:rwx ${path}
+	_evalr setfacl -Rm d:u:100000:rwx ${path}
 
 else
 	_exite "This part have to be implemented"
@@ -97,15 +123,15 @@ fi
 
 ########################  PROFILE
 
-profile=maria-${S_DOMAIN_FQDN}
-_echoT "----------  profiles ${profile}"
+profile=${_MDB_NAME}
+_echoT "----------  profile ${profile}"
 
 lxc profile list -f csv|grep -q "^${profile}," && _eval lxc profile rename ${profile} ${profile}.${_SDATE}
 _eval lxc profile create ${profile}
 
 path=${_MDB_HOST_PATH}
 path_ct=${_MDB_VM_PATH}
-[ -d ${path} ] || _eval mkdir -p ${path}
+[ -d ${path} ] || _evalr mkdir -p ${path}
 _eval lxc profile device add ${profile} ${profile} disk source=${path} path=${path_ct}
 
 
@@ -113,8 +139,8 @@ _eval lxc profile device add ${profile} ${profile} disk source=${path} path=${pa
 
 _echoT "----------  init"
 
-if lxc list -f json |jq -r '.[].name' | grep -q ^${_CT_NAME}$; then
-	if lxc list -f json | jq -r '.[] | select(.status == "Running").name' | grep -q ^${_CT_NAME}$; then
+if lxc list -f csv -c n | grep -q ^${_CT_NAME}$; then
+	if lxc list -f csv -c n status=Running | grep -q ^${_CT_NAME}$; then
 		_eval lxc stop ${_CT_NAME}
 		_eval lxc rename ${_CT_NAME} ${_CT_NAME}-${_SDATE}
 		_eval lxc start ${_CT_NAME}-${_SDATE}
@@ -125,51 +151,43 @@ fi
 
 _eval lxc init ${_CT_NAME_COM} ${_CT_NAME} -p default -p global -p ${profile}
 
-
-#_echoT "----------  network fixed ip"
-#
-#if ! lxc list -f json | jq -r '.[] | select(.name == "'${_CT_NAME}'").devices[].name' | grep -q eth0; then
-#	_eval lxc network attach ${s_inet} ${_CT_NAME} eth0 eth0
-#fi
-#_eval lxc config device set ${_CT_NAME} eth0 ipv4.address ${_CT_IP}
-
-
 _echoT "----------  ${_CT_NAME} start"
-
 _eval lxc start ${_CT_NAME}
-
-_eval sleep 1
 
 
 ########################  INSTALL
 
 _echoT "----------  update"
-
 _lxc_exec ${_CT_NAME} "apk update"
 
 _echoT "----------  install mariadb"
-
 _lxc_exec ${_CT_NAME} "apk add mariadb mariadb-client mariadb-mytop"
 
 _echoT "----------  initialize mariadb"
-
 _lxc_exec ${_CT_NAME} "mysql_install_db --user=mysql --datadir=${_MDB_VM_PATH}"
 
 _echoT "----------  service set & start"
-
 service=mariadb
 _lxc_exec ${_CT_NAME} "rc-update add ${service}"
 _lxc_exec ${_CT_NAME} "rc-service ${service} start"
 
 
+########################  PATH
+
+_echoT "----------  paths"
+paths="${_MDB_PATH_DATA} ${_MDB_PATH_BINLOG} ${_MDB_PATH_LOG}"
+for path in ${paths}; do
+	_lxc_exec ${_CT_NAME} "[ -d ${path} ] || mkdir -p ${path}"
+	_lxc_exec ${_CT_NAME} "chown mysql ${path}"
+done
+
+
 ########################  MYSQL INIT
 
 _echoT "----------  root passwd"
-
 _lxc_exec ${_CT_NAME} "mysqladmin -u root password ${_MDB_PWD_LOCAL}"
 
 _echoT "----------  secure"
-
 _echoI "Use this password: ${_MDB_PWD_LOCAL}"
 _lxc_exec ${_CT_NAME} "mysql_secure_installation"
 
@@ -178,9 +196,10 @@ _lxc_exec ${_CT_NAME} "mysql_secure_installation"
 
 _echoT "----------  conf server"
 
-file=${path_conf}/${file_server##*/}
+file=${_MDB_PATH_CONF}/${file_server##*/}
 _lxc_exec ${_CT_NAME} "[ -f ${file} ] && cp -a ${file} ${file}.${_SDATE}"
-_eval lxc file push ${file_server} ${_CT_NAME}/${file}
+_eval lxc file push ${file_server} ${_CT_NAME}${file}
+_lxc_var_replace ${_CT_NAME} ${file} mariadb
 
 
 ########################  PASSWORD
@@ -193,22 +212,26 @@ _echoT "----------  right rootadmin"
 
 for name in ${S_SERVICE[admin]}; do
 	strpass+="rootadmin @ ${name} - ${_MDB_PWD_ADMIN}\n"
-	_lxc_exec ${_CT_NAME} "mysql -uroot -p${_MDB_PWD_LOCAL} -e \"GRANT ALL PRIVILEGES ON *.* TO rootadmin@'${name}' IDENTIFIED BY '${_MDB_PWD_ADMIN}' WITH GRANT OPTION\""
+	cmd="GRANT ALL PRIVILEGES ON *.* TO rootadmin@'${name}' IDENTIFIED BY '${_MDB_PWD_ADMIN}' WITH GRANT OPTION"
+	_lxc_exec ${_CT_NAME} "mysql -uroot -p${_MDB_PWD_LOCAL} -e \"${cmd}\""
 done
 
 _echoT "----------  right roothost"
 
 for ip in ${_IPS_CLUSTER} ${_IP_HOST_VM}; do
 	strpass+="roothost @ ${ip} - ${_MDB_PWD_HOST}\n"
-	_lxc_exec ${_CT_NAME} "mysql -uroot -p${_MDB_PWD_LOCAL} -e \"GRANT ALL PRIVILEGES ON *.* TO roothost@'${ip}' IDENTIFIED BY '${_MDB_PWD_HOST}' WITH GRANT OPTION\""
+	cmd="GRANT ALL PRIVILEGES ON *.* TO roothost@'${ip}' IDENTIFIED BY '${_MDB_PWD_HOST}' WITH GRANT OPTION"
+	_lxc_exec ${_CT_NAME} "mysql -uroot -p${_MDB_PWD_LOCAL} -e \"${cmd}\""
 done
 
 _echoT "----------  right rootremote"
 
 for ip in ${S_IPS_ADMIN}; do
 	strpass+="rootremote @ ${ip} - ${_MDB_PWD_REMOTE}\n"
-	_lxc_exec ${_CT_NAME} "mysql -uroot -p${_MDB_PWD_LOCAL} -e \"GRANT ALL PRIVILEGES ON *.* TO rootremote@'${ip}' IDENTIFIED BY '${_MDB_PWD_REMOTE}' WITH GRANT OPTION\""
-	_lxc_exec ${_CT_NAME} "mysql -uroot -p${_MDB_PWD_LOCAL} -e \"GRANT PROXY ON ''@'%' TO 'rootremote'@'${ip}' WITH GRANT OPTION\""
+	cmd="GRANT ALL PRIVILEGES ON *.* TO rootremote@'${ip}' IDENTIFIED BY '${_MDB_PWD_REMOTE}' WITH GRANT OPTION"
+	_lxc_exec ${_CT_NAME} "mysql -uroot -p${_MDB_PWD_LOCAL} -e \"${cmd}\""
+	cmd="GRANT PROXY ON ''@'%' TO 'rootremote'@'${ip}' WITH GRANT OPTION"
+	_lxc_exec ${_CT_NAME} "mysql -uroot -p${_MDB_PWD_LOCAL} -e \"${cmd}\""
 done
 
 
@@ -278,6 +301,15 @@ _eval lxc file push ${file_logrotate_client} ${_CT_NAME}${file}
 _lxc_var_replace ${_CT_NAME} ${file} logrotate
 
 
+########################  PWD
+
+_echoT "----------  ${_CT_NAME} passwd"
+
+file=${S_PATH_CONF}/mariadb
+strpass= ${strpass%\\n}
+_lxc_exec ${_CT_NAME} "echo -e ${strpass//\\n/\\\\n} > ${file}"
+
+
 ########################  CLEAN LOG
 
 _echoT "----------  ${_CT_NAME} log clean"
@@ -285,19 +317,11 @@ _echoT "----------  ${_CT_NAME} log clean"
 _lxc_exec ${_CT_NAME} "find ${S_PATH_LOG}/mysql -name *.log -exec rm {} \;"
 
 
-########################  PUBLISH
-
-_echoT "----------  publish ${_CT_NAME}"
-
-_eval lxc image list -f json | jq -r '.[].aliases[].name' | grep -q ^${_CT_NAME}$ && lxc image alias rename ${_CT_NAME} ${_CT_NAME}-$(date +%s)
-_eval lxc publish --force ${_CT_NAME} --alias ${_CT_NAME}
-
-
 ########################  CLIENT
 
 _echoT "----------  host install mariadb-client"
 
-_eval apt install -y mariadb-client
+_install -y mariadb-client
 
 
 ########################  SHOW
@@ -305,30 +329,38 @@ _eval apt install -y mariadb-client
 _echoT "----------  show privileges"
 
 # show users
-_lxc_exec ${_CT_NAME} "mysql -uroot -p${_MDB_PWD_LOCAL} -e \"FLUSH PRIVILEGES\""
-#_evalq "mysql -uroot -p${_MDB_PWD_LOCAL} -e \"SELECT user,host FROM mysql.user WHERE Host <> 'localhost'\""
-_lxc_exec ${_CT_NAME} "mysql -uroot -p${_MDB_PWD_LOCAL} -e \"SELECT user,host FROM mysql.user\""
+_lxc_exec ${_CT_NAME} "mysql -uroot -p${_MDB_PWD_LOCAL} -e 'FLUSH PRIVILEGES'"
+_lxc_exec ${_CT_NAME} "mysql -uroot -p${_MDB_PWD_LOCAL} -e 'SELECT user,host FROM mysql.user'"
+#_lxc_exec ${_CT_NAME} "mysql -uroot -p${_MDB_PWD_LOCAL} -e \"SELECT user,host FROM mysql.user WHERE Host <> 'localhost'\""
 
 
 _echoT "----------  show passwords"
 
 # show users
 _echoI "Keep this passwords:"
-_echoW "${strpass%/n}"
+_echoW "${strpass}"
 
 
-########################  TEST
+#########################  TEST
 
 _echoT "----------  maria test"
 
 _echoI "To verify maria configuration, from the host type:"
-_echo "mysql -uroot -h${_CT_NAME} -p${_MDB_PWD_HOST} "
+_echo "mysql -uroothost -h${_CT_NAME} -p${_MDB_PWD_HOST} "
+
+
+#######################  PUBLISH
+
+_echoT "----------  publish ${_CT_NAME}"
+
+_eval lxc image list -f csv -c l | grep -q ^${_CT_NAME}$ && lxc image alias rename ${_CT_NAME} ${_CT_NAME}-$(date +%s)
+_eval lxc publish --force ${_CT_NAME} --alias ${_CT_NAME}
 
 
 ########################  END
 
-_echoT "---------- ${_PART} end"
-_eval "_partadd ${_PART} ${S_FILE_INSTALL_DONE}"
+_echoT "===================== ${_PART} end"
+#_partadd ${_PART} ${S_FILE_INSTALL_DONE}
 
 
 <<KEEP
@@ -355,10 +387,10 @@ mysql -uroot -p"${_MDB_PWD_LOCAL}" -e "SELECT ENGINE, COUNT(*) AS count FROM INF
 
 ######################## Restore root password
 rc-service mysql stop
-#kill  `cat /run/mysqld/mysqld.pid`
+kill  \$(cat /run/mysqld/mysqld.pid)
 /usr/bin/mysqld --datadir=/var/lib/mysql --pid-file=/run/mysqld/mysqld.pid --skip-grant-tables --skip-networking &
 mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'MyNewPass';FLUSH PRIVILEGES;ALTER USER 'root'@'localhost' IDENTIFIED BY 'MyNewPass';FLUSH PRIVILEGES;set password = password('MyNewPass');"
-#kill  `cat /run/mysqld/mysqld.pid`
+kill  \$(cat /run/mysqld/mysqld.pid)
 rc-service mariadb restart
 
 KEEP
diff --git a/sub/lxd-alpine-php.install b/sub/lxd-alpine-php.install
--- a/sub/lxd-alpine-php.install
+++ b/sub/lxd-alpine-php.install
@@ -4,15 +4,16 @@
 
 _echoT "\n==========================================  ${_RELEASE} ${_PART}"
 
+grep -q "^# ${_PART}$" ${S_FILE_INSTALL_CONF} || echo  "# ${_PART}" | _evalqr tee -a ${S_FILE_INSTALL_CONF}
 
 ########################  REQUIRED
 
 _echoT "------------------ required vm image"
-lxc image list -f json |jq -r '.[].aliases[].name' | grep -q ^${S_SERVICE[http]}$ || _exite "Unable to find image container: '${S_SERVICE[http]}"
+lxc image list -f csv -c l | grep -q ^${S_SERVICE[http]}$ || _exite "Unable to find image container: '${S_SERVICE[http]}"
 
 _echoT "------------------ required vm"
-lxc list -f json |jq -r '.[].name'| grep -q ^${S_SERVICE[log]}$ || _exite "Unable to find image container: '${S_SERVICE[log]}'"
-lxc list -f json |jq -r '.[].name'| grep -q ^${S_SERVICE[cache]}$ || _exite "Unable to find image container: '${S_SERVICE[cache]}'"
+lxc list -f csv -c n| grep -q ^${S_SERVICE[log]}$ || _exite "Unable to find image container: '${S_SERVICE[log]}'"
+lxc list -f csv -c n| grep -q ^${S_SERVICE[cache]}$ || _exite "Unable to find image container: '${S_SERVICE[cache]}'"
 
 
 file_phpfpm="${S_PATH_INSTALL_CONF}/apache2/php7-fpm.conf"
@@ -55,41 +56,41 @@ php_modules="php7-bcmath php7-bz2 php7-ctype php7-curl php7-exif php7-fileinfo p
 
 _echoT "----------  data php"
 
-[ -z ${_PHP_MAX_EXECUTION_TIME+x} ] && anstmp="20" && _askno "max_execution_time (${anstmp})s" && _PHP_MAX_EXECUTION_TIME=${_ANSWER:-$anstmp} && _confset _PHP_MAX_EXECUTION_TIME "${_PHP_MAX_EXECUTION_TIME}"
+[ -z ${_PHP_MAX_EXECUTION_TIME+x} ] && anstmp="20" && _askno "max_execution_time (${anstmp})s" && _PHP_MAX_EXECUTION_TIME="${_ANSWER:-$anstmp}" && _confset _PHP_MAX_EXECUTION_TIME "${_PHP_MAX_EXECUTION_TIME}"
 
-[ -z ${_PHP_MAX_INPUT_TIME+x} ] && anstmp="30" && _askno "max_input_time (${anstmp})s" && _PHP_MAX_INPUT_TIME=${_ANSWER:-$anstmp} && _confset _PHP_MAX_INPUT_TIME "${_PHP_MAX_INPUT_TIME}"
+[ -z ${_PHP_MAX_INPUT_TIME+x} ] && anstmp="30" && _askno "max_input_time (${anstmp})s" && _PHP_MAX_INPUT_TIME="${_ANSWER:-$anstmp}" && _confset _PHP_MAX_INPUT_TIME "${_PHP_MAX_INPUT_TIME}"
 
-[ -z ${_PHP_MEMORY_LIMIT+x} ] && anstmp="128M" && _askno "memory_limit (${anstmp})" && _PHP_MEMORY_LIMIT=${_ANSWER:-$anstmp} && _confset _PHP_MEMORY_LIMIT "${_PHP_MEMORY_LIMIT}"
+[ -z ${_PHP_MEMORY_LIMIT+x} ] && anstmp="128M" && _askno "memory_limit (${anstmp})" && _PHP_MEMORY_LIMIT="${_ANSWER:-$anstmp}" && _confset _PHP_MEMORY_LIMIT "${_PHP_MEMORY_LIMIT}"
 
-[ -z ${_PHP_POST_MAX_SIZE+x} ] && anstmp="8M" && _askno "post_max_size (${anstmp})" && _PHP_POST_MAX_SIZE=${_ANSWER:-$anstmp} && _confset _PHP_POST_MAX_SIZE "${_PHP_POST_MAX_SIZE}"
+[ -z ${_PHP_POST_MAX_SIZE+x} ] && anstmp="8M" && _askno "post_max_size (${anstmp})" && _PHP_POST_MAX_SIZE="${_ANSWER:-$anstmp}" && _confset _PHP_POST_MAX_SIZE "${_PHP_POST_MAX_SIZE}"
 
-[ -z ${_PHP_UPLOAD_MAX_FILESIZE+x} ] && anstmp="8M" && _askno "upload_max_filesize (${anstmp})" && _PHP_UPLOAD_MAX_FILESIZE=${_ANSWER:-$anstmp} && _confset _PHP_UPLOAD_MAX_FILESIZE "${_PHP_UPLOAD_MAX_FILESIZE}"
+[ -z ${_PHP_UPLOAD_MAX_FILESIZE+x} ] && anstmp="8M" && _askno "upload_max_filesize (${anstmp})" && _PHP_UPLOAD_MAX_FILESIZE="${_ANSWER:-$anstmp}" && _confset _PHP_UPLOAD_MAX_FILESIZE "${_PHP_UPLOAD_MAX_FILESIZE}"
 
-[ -z ${_PHP_SESSION_STRICT_MODE+x} ] && anstmp="1" && _askno "session.use_strict_mode (${anstmp})" && _PHP_SESSION_STRICT_MODE=${_ANSWER:-$anstmp} && _confset _PHP_SESSION_STRICT_MODE "${_PHP_SESSION_STRICT_MODE}"
+[ -z ${_PHP_SESSION_STRICT_MODE+x} ] && anstmp="1" && _askno "session.use_strict_mode (${anstmp})" && _PHP_SESSION_STRICT_MODE="${_ANSWER:-$anstmp}" && _confset _PHP_SESSION_STRICT_MODE "${_PHP_SESSION_STRICT_MODE}"
 
-[ -z ${_PHP_MODULES+x} ] && anstmp="${php_modules}" && _askno "php modules to install: \n${anstmp}" && _PHP_MODULES=${_ANSWER:-$anstmp} && _confset _PHP_MODULES "${_PHP_MODULES}"
+[ -z ${_PHP_MODULES+x} ] && anstmp="${php_modules}" && _askno "php modules to install: \n${anstmp}" && _PHP_MODULES="${_ANSWER:-$anstmp}" && _confset _PHP_MODULES "${_PHP_MODULES}"
 
 _echoT "----------  data php-fpm"
 
-[ -z ${_PHP_RESTART_THRESHOLD+x} ] && anstmp='30' && _askno "Give value for 'emergency_restart_threshold' ($anstmp)" && _PHP_RESTART_THRESHOLD=${_ANSWER:-$anstmp} && _confset _PHP_RESTART_THRESHOLD "${_PHP_RESTART_THRESHOLD}"
+[ -z ${_PHP_RESTART_THRESHOLD+x} ] && anstmp='30' && _askno "Give value for 'emergency_restart_threshold' ($anstmp)" && _PHP_RESTART_THRESHOLD="${_ANSWER:-$anstmp}" && _confset _PHP_RESTART_THRESHOLD "${_PHP_RESTART_THRESHOLD}"
 
-[ -z ${_PHP_RESTART_INTERVAL+x} ] && anstmp='60s' && _askno "Give value for 'emergency_restart_interval' ($anstmp)" && _PHP_RESTART_INTERVAL=${_ANSWER:-$anstmp} && _confset _PHP_RESTART_INTERVAL "${_PHP_RESTART_INTERVAL}"
+[ -z ${_PHP_RESTART_INTERVAL+x} ] && anstmp='60s' && _askno "Give value for 'emergency_restart_interval' ($anstmp)" && _PHP_RESTART_INTERVAL="${_ANSWER:-$anstmp}" && _confset _PHP_RESTART_INTERVAL "${_PHP_RESTART_INTERVAL}"
 
-[ -z ${_PHP_CONTROL_TIMEOUT+x} ] && anstmp='0' && _askno "Give value for 'process_control_timeout' ($anstmp)s" && _PHP_CONTROL_TIMEOUT=${_ANSWER:-$anstmp} && _confset _PHP_CONTROL_TIMEOUT "${_PHP_CONTROL_TIMEOUT}"
+[ -z ${_PHP_CONTROL_TIMEOUT+x} ] && anstmp='0' && _askno "Give value for 'process_control_timeout' ($anstmp)s" && _PHP_CONTROL_TIMEOUT="${_ANSWER:-$anstmp}" && _confset _PHP_CONTROL_TIMEOUT "${_PHP_CONTROL_TIMEOUT}"
 
 _echoT "----------  data pool www"
 
-[ -z ${_PHP_W_MAX_CHILDREN+x} ] && anstmp='20' && _askno "Give value for 'pm.max_children' ($anstmp)" && _PHP_W_MAX_CHILDREN=${_ANSWER:-$anstmp} && _confset _PHP_W_MAX_CHILDREN "${_PHP_W_MAX_CHILDREN}"
+[ -z ${_PHP_W_MAX_CHILDREN+x} ] && anstmp='20' && _askno "Give value for 'pm.max_children' ($anstmp)" && _PHP_W_MAX_CHILDREN="${_ANSWER:-$anstmp}" && _confset _PHP_W_MAX_CHILDREN "${_PHP_W_MAX_CHILDREN}"
 
-[ -z ${_PHP_W_START_SERVERS+x} ] && anstmp='4' && _askno "Give value for 'pm.start_servers' ($anstmp)" && _PHP_W_START_SERVERS=${_ANSWER:-$anstmp} && _confset _PHP_W_START_SERVERS "${_PHP_W_START_SERVERS}"
+[ -z ${_PHP_W_START_SERVERS+x} ] && anstmp='4' && _askno "Give value for 'pm.start_servers' ($anstmp)" && _PHP_W_START_SERVERS="${_ANSWER:-$anstmp}" && _confset _PHP_W_START_SERVERS "${_PHP_W_START_SERVERS}"
 
-[ -z ${_PHP_W_MIN_SPARE_SERVERS+x} ] && anstmp='4' && _askno "Give value for 'pm.min_spare_servers' ($anstmp)" && _PHP_W_MIN_SPARE_SERVERS=${_ANSWER:-$anstmp} && _confset _PHP_W_MIN_SPARE_SERVERS "${_PHP_W_MIN_SPARE_SERVERS}"
+[ -z ${_PHP_W_MIN_SPARE_SERVERS+x} ] && anstmp='4' && _askno "Give value for 'pm.min_spare_servers' ($anstmp)" && _PHP_W_MIN_SPARE_SERVERS="${_ANSWER:-$anstmp}" && _confset _PHP_W_MIN_SPARE_SERVERS "${_PHP_W_MIN_SPARE_SERVERS}"
 
-[ -z ${_PHP_W_MAX_SPARE_SERVERS+x} ] && anstmp='15' && _askno "Give value for 'pm.max_spare_servers' ($anstmp)" && _PHP_W_MAX_SPARE_SERVERS=${_ANSWER:-$anstmp} && _confset _PHP_W_MAX_SPARE_SERVERS "${_PHP_W_MAX_SPARE_SERVERS}"
+[ -z ${_PHP_W_MAX_SPARE_SERVERS+x} ] && anstmp='15' && _askno "Give value for 'pm.max_spare_servers' ($anstmp)" && _PHP_W_MAX_SPARE_SERVERS="${_ANSWER:-$anstmp}" && _confset _PHP_W_MAX_SPARE_SERVERS "${_PHP_W_MAX_SPARE_SERVERS}"
 
-[ -z ${_PHP_W_MAX_REQUESTS+x} ] && anstmp='100000' && _askno "Give value for 'pm.max_requests' ($anstmp)" && _PHP_W_MAX_REQUESTS=${_ANSWER:-$anstmp} && _confset _PHP_W_MAX_REQUESTS "${_PHP_W_MAX_REQUESTS}"
+[ -z ${_PHP_W_MAX_REQUESTS+x} ] && anstmp='100000' && _askno "Give value for 'pm.max_requests' ($anstmp)" && _PHP_W_MAX_REQUESTS="${_ANSWER:-$anstmp}" && _confset _PHP_W_MAX_REQUESTS "${_PHP_W_MAX_REQUESTS}"
 
-[ -z ${_PHP_SLOWLOG_TIMEOUT+x} ] && anstmp='2' && _askno "Give value for 'request_SLOWLOG_TIMEOUT' ($anstmp)" && _PHP_SLOWLOG_TIMEOUT=${_ANSWER:-$anstmp} && _confset _PHP_SLOWLOG_TIMEOUT "${_PHP_SLOWLOG_TIMEOUT}"
+[ -z ${_PHP_SLOWLOG_TIMEOUT+x} ] && anstmp='2' && _askno "Give value for 'request_SLOWLOG_TIMEOUT' ($anstmp)" && _PHP_SLOWLOG_TIMEOUT="${_ANSWER:-$anstmp}" && _confset _PHP_SLOWLOG_TIMEOUT "${_PHP_SLOWLOG_TIMEOUT}"
 
 
 ########################  PROFILE
@@ -102,7 +103,7 @@ _eval lxc profile create ${profile}
 
 path=${S_HOST_PATH_SHARE}/php/${S_DOMAIN_FQDN}
 path_ct=${path_php_share}
-[ -d ${path} ] || _eval mkdir -p ${path}
+[ -d ${path} ] || _evalr mkdir -p ${path}
 _eval lxc profile device add ${profile} ${profile} disk source=${path} path=${path_ct}
 
 
@@ -110,8 +111,8 @@ _eval lxc profile device add ${profile} ${profile} disk source=${path} path=${pa
 
 _echoT "----------  init"
 
-if lxc list -f json |jq -r '.[].name' | grep -q ^${_CT_NAME}$; then
-	if lxc list -f json | jq -r '.[] | select(.status == "Running").name' | grep -q ^${_CT_NAME}$; then
+if lxc list -f csv -c n | grep -q ^${_CT_NAME}$; then
+	if lxc list -f csv -c n status=Running| grep -q ^${_CT_NAME}$; then
 		_eval lxc stop ${_CT_NAME}
 		_eval lxc rename ${_CT_NAME} ${_CT_NAME}-${_SDATE}
 		_eval lxc start ${_CT_NAME}-${_SDATE}
@@ -132,10 +133,7 @@ _eval lxc init ${S_SERVICE[http]} ${_CT_NAME} -p default -p global -p www-${S_DO
 
 
 _echoT "----------  ${_CT_NAME} start"
-
 _eval lxc start ${_CT_NAME}
-
-_eval sleep 1
 
 
 ########################  PATHS
@@ -318,7 +316,7 @@ _lxc_exec ${_CT_NAME} "${cmds}"
 _echoT "----------  apache php-fpm"
 
 file=${path_apache_conf}/${file_phpfpm##*/}
-_eval lxc file push ${file_phpfpm} ${_CT_NAME}/${file}
+_eval lxc file push ${file_phpfpm} ${_CT_NAME}${file}
 _lxc_var_replace ${_CT_NAME} ${file} php apache
 
 
@@ -354,7 +352,7 @@ _echoT "----------  ping-monitor conf"
 
 file=${path_apache_conf}/${file_monitor##*/}
 _keepcpts ${file}
-_eval lxc file push ${file_monitor} ${_CT_NAME}/${file}
+_eval lxc file push ${file_monitor} ${_CT_NAME}${file}
 _lxc_var_replace ${_CT_NAME} ${file} apache php
 
 
@@ -364,13 +362,13 @@ _echoT "----------  opcache file"
 
 url=https://raw.githubusercontent.com/rlerdorf/opcache-status/master/opcache.php
 file=${_APA_PATH_WWW}/opcache.php
-_lxc_exec ${_CT_NAME} "wget ${url} -O ${file}"
+_lxc_exec ${_CT_NAME} "wget -q ${url} -O ${file}"
 
 _echoT "----------  opcache conf"
 
 file=${path_apache_conf}/${file_opcache##*/}
 _keepcpts ${file}
-_eval lxc file push ${file_opcache} ${_CT_NAME}/${file}
+_eval lxc file push ${file_opcache} ${_CT_NAME}${file}
 _lxc_var_replace ${_CT_NAME} ${file} apache php
 
 
@@ -379,7 +377,7 @@ _lxc_var_replace ${_CT_NAME} ${file} apache php
 _echoT "----------  ${S_SERVICE[proxy]} ${S_DOMAIN_NAME}1 "
 
 file=/etc/haproxy/conf-available/80-backends
-_lxc_exec ${S_SERVICE[proxy]} "sed -i 's|^\(\s*server\s*${S_DOMAIN_NAME}1\s*\).*\(:80 .*\)$|\1${S_SERVICE[php]}\2|' ${file}"
+_lxc_exec ${S_SERVICE[proxy]} "sed -i 's|${S_SERVICE[http]}|${S_SERVICE[php]}|' ${file}"
 
 
 ########################  RESTART
@@ -452,14 +450,6 @@ _echoT "----------  ${_CT_NAME} log clean"
 _lxc_exec ${_CT_NAME} "find ${S_PATH_LOG}/php7 -name *.log -exec rm {} \;"
 
 
-########################  PUBLISH
-
-_echoT "----------  publish ${_CT_NAME}"
-
-_eval lxc image list -f json | jq -r '.[].aliases[].name' | grep -q ^${_CT_NAME}$ && lxc image alias rename ${_CT_NAME} ${_CT_NAME}-$(date +%s)
-_eval lxc publish --force ${_CT_NAME} --alias ${_CT_NAME}
-
-
 ########################  TEST
 
 _echoT "----------  php test"
@@ -485,7 +475,15 @@ _echo "curl ${_CT_NAME}/status-www-admin"
 _echo "curl ${_CT_NAME}/status-www-admin?full"
 
 
+########################  PUBLISH
+
+_echoT "----------  publish ${_CT_NAME}"
+
+_eval lxc image list -f csv -c l | grep -q ^${_CT_NAME}$ && lxc image alias rename ${_CT_NAME} ${_CT_NAME}-$(date +%s)
+_eval lxc publish --force ${_CT_NAME} --alias ${_CT_NAME}
+
+
 ########################  END
 
-_echoT "---------- ${_PART} end"
-_eval "_partadd ${_PART} ${S_FILE_INSTALL_DONE}"
+_echoT "===================== ${_PART} end"
+_partadd ${_PART} ${S_FILE_INSTALL_DONE}
diff --git a/sub/lxd-alpine-redis.install b/sub/lxd-alpine-redis.install
--- a/sub/lxd-alpine-redis.install
+++ b/sub/lxd-alpine-redis.install
@@ -4,15 +4,16 @@
 
 _echoT "\n==========================================  ${_RELEASE} ${_PART}"
 
+grep -q "^# ${_PART}$" ${S_FILE_INSTALL_CONF} || echo  "# ${_PART}" | _evalqr tee -a ${S_FILE_INSTALL_CONF}
 
 ########################  REQUIRED
 
 _echoT "------------------ required vm image"
-lxc image list -f json |jq -r '.[].aliases[].name' | grep -q ^${_CT_NAME_COM}$ || _exite "Unable to find image container: '${_CT_NAME_COM}'"
+lxc image list -f csv -c l | grep -q ^${_CT_NAME_COM}$ || _exite "Unable to find image container: '${_CT_NAME_COM}'"
 
 _echoT "------------------ required vm"
-lxc list -f json | jq -r '.[].name' | grep -q ^${S_SERVICE[log]}$ || _exite "Unable to find image container: '${S_SERVICE[log]}'"
-lxc list -f json | jq -r '.[].name' | grep -q ^${S_SERVICE[http]}$ || _exite "Unable to find image container: '${S_SERVICE[http]}'"
+lxc list -f csv -c n | grep -q ^${S_SERVICE[log]}$ || _exite "Unable to find image container: '${S_SERVICE[log]}'"
+lxc list -f csv -c n | grep -q ^${S_SERVICE[http]}$ || _exite "Unable to find image container: '${S_SERVICE[http]}'"
 
 file_rsyslog_host=${S_PATH_INSTALL_CONF}/rsyslog/host-redis.conf
 file_rsyslog_client=${S_PATH_INSTALL_CONF}/rsyslog/client-redis.conf
@@ -34,30 +35,30 @@ _CT_NAME=${S_SERVICE[cache]}
 
 _echoT "----------  data sysctl.conf"
 
-[ -z ${_RDS_MAX_SYN_BACKLOG+x} ] && anstmp="${_MAX_SYN_BACKLOG}" && _askno "Set $(sysctl net.ipv4.tcp_max_syn_backlog) - (${anstmp})" && _RDS_MAX_SYN_BACKLOG=${_ANSWER:-$anstmp} && _confset _RDS_MAX_SYN_BACKLOG "${_RDS_MAX_SYN_BACKLOG}"
+[ -z ${_RDS_MAX_SYN_BACKLOG+x} ] && anstmp="${_MAX_SYN_BACKLOG}" && _askno "Set $(sysctl net.ipv4.tcp_max_syn_backlog) - (${anstmp})" && _RDS_MAX_SYN_BACKLOG="${_ANSWER:-$anstmp}" && _confset _RDS_MAX_SYN_BACKLOG "${_RDS_MAX_SYN_BACKLOG}"
 
-[ -z ${_RDS_MAX_TW_BUCKETS+x} ] && anstmp="${_MAX_TW_BUCKETS}" && _askno "Set $(sysctl net.ipv4.tcp_max_tw_buckets) - (${anstmp})" && _RDS_MAX_TW_BUCKETS=${_ANSWER:-$anstmp} && _confset _RDS_MAX_TW_BUCKETS "${_RDS_MAX_TW_BUCKETS}"
+[ -z ${_RDS_MAX_TW_BUCKETS+x} ] && anstmp="${_MAX_TW_BUCKETS}" && _askno "Set $(sysctl net.ipv4.tcp_max_tw_buckets) - (${anstmp})" && _RDS_MAX_TW_BUCKETS="${_ANSWER:-$anstmp}" && _confset _RDS_MAX_TW_BUCKETS "${_RDS_MAX_TW_BUCKETS}"
 
-[ -z ${_RDS_FIN_TIMEOUT+x} ] && anstmp="${_FIN_TIMEOUT}" && _askno "Set $(sysctl net.ipv4.tcp_fin_timeout) - (${anstmp})" && _RDS_FIN_TIMEOUT=${_ANSWER:-$anstmp} && _confset _RDS_FIN_TIMEOUT "${_RDS_FIN_TIMEOUT}"
+[ -z ${_RDS_FIN_TIMEOUT+x} ] && anstmp="${_FIN_TIMEOUT}" && _askno "Set $(sysctl net.ipv4.tcp_fin_timeout) - (${anstmp})" && _RDS_FIN_TIMEOUT="${_ANSWER:-$anstmp}" && _confset _RDS_FIN_TIMEOUT "${_RDS_FIN_TIMEOUT}"
 
-[ -z ${_RDS_KEEPALIVE_TIME+x} ] && anstmp="240" && _askno "Set $(sysctl net.ipv4.tcp_keepalive_time) - (${anstmp})" && _RDS_KEEPALIVE_TIME=${_ANSWER:-$anstmp} && _confset _RDS_KEEPALIVE_TIME "${_RDS_KEEPALIVE_TIME}"
+[ -z ${_RDS_KEEPALIVE_TIME+x} ] && anstmp="240" && _askno "Set $(sysctl net.ipv4.tcp_keepalive_time) - (${anstmp})" && _RDS_KEEPALIVE_TIME="${_ANSWER:-$anstmp}" && _confset _RDS_KEEPALIVE_TIME "${_RDS_KEEPALIVE_TIME}"
 
-[ -z ${_RDS_KEEPALIVE_INTVL+x} ] && anstmp="30" && _askno "Set $(sysctl net.ipv4.tcp_keepalive_intvl) - (${anstmp})" && _RDS_KEEPALIVE_INTVL=${_ANSWER:-$anstmp} && _confset _RDS_KEEPALIVE_INTVL "${_RDS_KEEPALIVE_INTVL}"
+[ -z ${_RDS_KEEPALIVE_INTVL+x} ] && anstmp="30" && _askno "Set $(sysctl net.ipv4.tcp_keepalive_intvl) - (${anstmp})" && _RDS_KEEPALIVE_INTVL="${_ANSWER:-$anstmp}" && _confset _RDS_KEEPALIVE_INTVL "${_RDS_KEEPALIVE_INTVL}"
 
-[ -z ${_RDS_KEEPALIVE_PROBES+x} ] && anstmp="9" && _askno "Set $(sysctl net.ipv4.tcp_keepalive_probes) - (${anstmp})" && _RDS_KEEPALIVE_PROBES=${_ANSWER:-$anstmp} && _confset _RDS_KEEPALIVE_PROBES "${_RDS_KEEPALIVE_PROBES}"
+[ -z ${_RDS_KEEPALIVE_PROBES+x} ] && anstmp="9" && _askno "Set $(sysctl net.ipv4.tcp_keepalive_probes) - (${anstmp})" && _RDS_KEEPALIVE_PROBES="${_ANSWER:-$anstmp}" && _confset _RDS_KEEPALIVE_PROBES "${_RDS_KEEPALIVE_PROBES}"
 
 
 _echoT "----------  data redis"
 
-[ -z "${_RDS_BACKLOG+x}" ] && anstmp="$(( ${_RDS_MAX_SYN_BACKLOG} / 2 ))" && _askno "Give a value for 'tcp-backlog', if change adjust sysctl parameters... (${anstmp})" && _RDS_BACKLOG=${_ANSWER:-$anstmp} && _confset _RDS_BACKLOG "${_RDS_BACKLOG}"
+[ -z "${_RDS_BACKLOG+x}" ] && anstmp="$(( ${_RDS_MAX_SYN_BACKLOG} / 2 ))" && _askno "Give a value for 'tcp-backlog', if change adjust sysctl parameters... (${anstmp})" && _RDS_BACKLOG="${_ANSWER:-$anstmp}" && _confset _RDS_BACKLOG "${_RDS_BACKLOG}"
 
-[ -z "${_RDS_KEEPALIVE+x}" ] && anstmp="$(( ${_APA_KEEPALIVE_TIME} + 60 ))" && _askno "Give time to keep alive (sends acks) 'tcp-keepalive' (${anstmp})s" && _RDS_KEEPALIVE=${_ANSWER:-$anstmp} && _confset _RDS_KEEPALIVE "${_RDS_KEEPALIVE}"
+[ -z "${_RDS_KEEPALIVE+x}" ] && anstmp="$(( ${_APA_KEEPALIVE_TIME} + 60 ))" && _askno "Give time to keep alive (sends acks) 'tcp-keepalive' (${anstmp})s" && _RDS_KEEPALIVE="${_ANSWER:-$anstmp}" && _confset _RDS_KEEPALIVE "${_RDS_KEEPALIVE}"
 
-[ -z "${_RDS_TIMEOUT+x}" ] && anstmp="3600" && _askno "Give time to idle connection 'timeout' (${anstmp})s" && _RDS_TIMEOUT=${_ANSWER:-$anstmp} && _confset _RDS_TIMEOUT "${_RDS_TIMEOUT}"
+[ -z "${_RDS_TIMEOUT+x}" ] && anstmp="3600" && _askno "Give time to idle connection 'timeout' (${anstmp})s" && _RDS_TIMEOUT="${_ANSWER:-$anstmp}" && _confset _RDS_TIMEOUT "${_RDS_TIMEOUT}"
 
-[ -z "${_RDS_DATABASES+x}" ] && anstmp="16" && _askno "Give a number of max 'databases' (${anstmp})" && _RDS_DATABASES=${_ANSWER:-$anstmp} && _confset _RDS_DATABASES "${_RDS_DATABASES}"
+[ -z "${_RDS_DATABASES+x}" ] && anstmp="16" && _askno "Give a number of max 'databases' (${anstmp})" && _RDS_DATABASES="${_ANSWER:-$anstmp}" && _confset _RDS_DATABASES "${_RDS_DATABASES}"
 
-[ -z "${_RDS_LOGLEVEL+x}" ] && anstmp="notice" && _askno "Give the log level 'loglevel': debug/verbose/notice/warning  (${anstmp})" && _RDS_LOGLEVEL=${_ANSWER:-$anstmp} && _confset _RDS_LOGLEVEL "${_RDS_LOGLEVEL}"
+[ -z "${_RDS_LOGLEVEL+x}" ] && anstmp="notice" && _askno "Give the log level 'loglevel': debug/verbose/notice/warning  (${anstmp})" && _RDS_LOGLEVEL="${_ANSWER:-$anstmp}" && _confset _RDS_LOGLEVEL "${_RDS_LOGLEVEL}"
 
 
 ########################  INIT
@@ -65,8 +66,8 @@ _echoT "----------  data redis"
 _echoT "----------  init"
 
 ! lxc image list -f json|jq -r '.[].aliases[].name'|grep -q ^${_CT_NAME_COM}$ && _exite "Unable to find image container '${_CT_NAME_COM}'"
-if lxc list -f json |jq -r '.[].name' | grep -q ^${_CT_NAME}$; then
-	if lxc list -f json | jq -r '.[] | select(.status == "Running").name' | grep -q ^${_CT_NAME}$; then
+if lxc list -f csv -c n | grep -q ^${_CT_NAME}$; then
+	if lxc list -f csv -c n status=Running | grep -q ^${_CT_NAME}$; then
 		_eval lxc stop ${_CT_NAME}
 		_eval lxc rename ${_CT_NAME} ${_CT_NAME}-${_SDATE}
 		_eval lxc start ${_CT_NAME}-${_SDATE}
@@ -79,19 +80,8 @@ fi
 _eval lxc init ${_CT_NAME_COM} ${_CT_NAME} -p default -p global
 
 
-#_echoT "----------  network fixed ip"
-#
-#if ! lxc list -f json | jq -r '.[] | select(.name == "'${_CT_NAME}'").devices[].name' | grep -q eth0; then
-#	_eval lxc network attach ${s_inet} ${_CT_NAME} eth0 eth0
-#fi
-#_eval lxc config device set ${_CT_NAME} eth0 ipv4.address ${_CT_IP}
-
-
 _echoT "----------  ${_CT_NAME} start"
-
 _eval lxc start ${_CT_NAME}
-
-_eval sleep 1
 
 
 ########################  SYSCTL
@@ -112,17 +102,14 @@ _lxc_exec ${_CT_NAME} "echo '${txt}' > ${file}"
 ########################  INSTALL
 
 _echoT "----------  host install"
-
-_eval apt install -y redis-tools
+_install -y redis-tools
 
 
 _echoT "----------  install"
-
 _lxc_exec ${_CT_NAME} "apk update"
 _lxc_exec ${_CT_NAME} "apk add redis"
 
 _echoT "----------  service set"
-
 service=redis
 _lxc_exec ${_CT_NAME} "rc-update add ${service}"
 _lxc_exec ${_CT_NAME} "rc-service ${service} start"
@@ -196,16 +183,7 @@ _lxc_exec ${_CT_NAME} "rc-service rsyslog restart"
 ########################  CLEAN LOG
 
 _echoT "----------  ${_CT_NAME} log clean"
-
 _lxc_exec ${_CT_NAME} "find ${S_PATH_LOG}/redis -name *.log -exec rm {} \;"
-
-
-########################  PUBLISH
-
-_echoT "----------  publish ${_CT_NAME}"
-
-_eval lxc image list -f json | jq -r '.[].aliases[].name' | grep -q ^${_CT_NAME}$ && lxc image alias rename ${_CT_NAME} ${_CT_NAME}-$(date +%s)
-_eval lxc publish --force ${_CT_NAME} --alias ${_CT_NAME}
 
 
 ########################  TEST
@@ -213,7 +191,7 @@ _eval lxc publish --force ${_CT_NAME} --alias ${_CT_NAME}
 _echoT "----------  redis test acces"
 
 _echo "timeout 3 redis-cli -h ${_CT_NAME} ping"
-_evalq "timeout 3 redis-cli -h ${_CT_NAME} ping 2>/dev/null"
+_eval "timeout 3 redis-cli -h ${_CT_NAME} ping 2>/dev/null"
 
 _echoI "\nTo do a benchmark, just type:" && sleep 0.1
 _echo "redis-benchmark -h ${_CT_NAME} -p ${S_CACHE_PORT} -n 1000 -c 10 -k 1 -q"
@@ -222,7 +200,15 @@ _echoI "\nTo see latency, just type:" && sleep 0.1
 _echo "redis-cli -h ${_CT_NAME} -p ${S_CACHE_PORT} --latency-dist"
 
 
+########################  PUBLISH
+
+_echoT "----------  publish ${_CT_NAME}"
+
+_eval lxc image list -f csv -c l | grep -q ^${_CT_NAME}$ && lxc image alias rename ${_CT_NAME} ${_CT_NAME}-$(date +%s)
+_eval lxc publish --force ${_CT_NAME} --alias ${_CT_NAME}
+
+
 ########################  END
 
-_echoT "---------- ${_PART} end"
-_eval "_partadd ${_PART} ${S_FILE_INSTALL_DONE}"
+_echoT "===================== ${_PART} end"
+_partadd ${_PART} ${S_FILE_INSTALL_DONE}
